### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by Yamakaky** [baskerville/plato#1]
Do you have any? Run cargo and put the bin somewhere?

**Comment by baskerville** [comment]
Please note that building with or without `--features importer` will generate different binaries.

The importer is meant to be used locally, and as you already guessed, you can just copy the binary in your path.

But building the reader requires more involvement (the target is `arm-unknown-linux-gnueabihf`): I'm therefore providing pre-built binaries on the release page.

I've added some installation steps to the guide.

**Comment by lilianmoraru** [comment]
Unrelated to this issue but hopefully this will be seen.

@Yamakaky Can you please share you decision on this?: https://github.com/rust-lang-nursery/rust-cookbook/issues/209
