### ISSUE TITLE
How to install via KSM?

### ISSUE THREAD

**Issue by ghost** [baskerville/plato#10]
I downloaded the KSM version of plato, and I added the `plato` folder to `.adds`. 

But how do I start it? It doesn't show up in the KSM like koreader does.

**Comment by taosxx** [comment]
Which version of KSM? KSM09 should already have a menu entry for plato. For KSM08, you have to copy a [script](https://www.mobileread.com/forums/showpost.php?p=3627890&postcount=36) to KSM's user script folder.

**Comment by MoeSattler** [comment]
KSM09. For me it just didnt show.

**Comment by taosxx** [comment]
What exactly did you copy to `.adds`? The `plato` folders inside [plato-0.3.2.zip](https://github.com/baskerville/plato/files/1606607/plato-0.3.2.zip) and [plato-launcher-ksm-0.3.2.zip](https://github.com/baskerville/plato/files/1606609/plato-launcher-ksm-0.3.2.zip)? I think the first one in combination with KSM09 should be enough. For me, a menu entry `start plato` appeared directly under `start koreader`. But for someone else it could maybe also be hiding behind `Toggle btw full and short menu`.
