### ISSUE TITLE
Why were Docker / GitHub Actions removed?

### ISSUE THREAD

**Issue by welps** [baskerville/plato#104]
Why were Docker and the GitHub action hooks removed in c4a5e043527fa575586fd2b22cbc646e2bedc10c?

I find it concerning that it doesn't seem the points made in #75 were understood at all.

If this was made in error or an issue was encountered, please let me know what I need to do to fix it. Thanks.

**Comment by baskerville** [comment]
The GitHub actions got in the way of the developer interactions during #101.

From a technical point of view, building on *Linux* now relies on the version of *MuPDF* provided by the system's package manager. The problem is that we target *MuPDF 1.16.1* and *Ubuntu* only has *1.15.0*.

**Comment by welps** [comment]
Okay, this is not a difficult fix. I will handle it in the afternoon (I'm `EDT`). Feel free to add me to notifications in the future as I'm happy to help.

**Comment by welps** [comment]
Handled in #105
