### ISSUE TITLE
Doesn't work on the Kobo Aura Version 2

### ISSUE THREAD

**Issue by onodera-punpun** [baskerville/plato#11]
See title, upon launch of plato (using fmon) it displays an `Oops! This document couldn't be opened.`

**Comment by baskerville** [comment]
There was a problem with the archive posted yesterday.

Could you re-download `plato-0.3.3.zip` and try again?

It you get a crash, please provide the content of `crash.log`.

**Comment by baskerville** [comment]
Regarding the error message (I now understand that it comes from *Nickel* (Kobo's UI)): what you should do is:
- Remove `plato.png` using *Nickel*.
- Connect your device and extract `plato-launcher-fmon-0.3.3.zip` to the root of the SD card.
- Eject the SD card.
- Add `plato.png` to a collection and open it.
- Power off and restart the device.

**Comment by onodera-punpun** [comment]
Let me try this, I have a question though: what is the point of the collection step?

**Comment by onodera-punpun** [comment]
(closed by accident)

**Comment by onodera-punpun** [comment]
Alright got it working :)

**Comment by baskerville** [comment]
> I have a question though: what is the point of the collection step?

This step triggers the thumbnail creation process: we don't want this to append when we have a watch on the icon, otherwise we'll receive an unsolicited *Open* event and execute the associated script.
