### ISSUE TITLE
Upgrade MuPDF to 1.17.0

### ISSUE THREAD

**Issue by baskerville** [baskerville/plato#110]
This would allow me to remove the fix for [bug 701476](https://bugs.ghostscript.com/show_bug.cgi?id=701476) in `kobo.patch`.

@welps Is this version available in *debian testing* yet?

**Comment by welps** [comment]
It's not, but that's only being used on the [dev image](https://github.com/baskerville/plato/blob/master/Dockerfile.dev#L16), the [armhf image](https://github.com/baskerville/plato/blob/master/Dockerfile#L17) uses your existing workflow so it would be unaffected.

**Comment by baskerville** [comment]
I wasn't concerned about the *armhf* image, but about the *dev* image: it will break as soon as I change the [related constant](https://github.com/baskerville/plato/blob/932c6634fad4ce82f676957a88df70906f3695f1/src/document/mupdf_sys.rs#L6).

**Comment by welps** [comment]
I see. You should feel free to move ahead with your change. I can repair the breakage by adding a shim until it makes it into testing and log an issue to remove the shim when it does.

**Comment by welps** [comment]
In the future, you should feel free to make progress and break the image functionality if necessary, just notify me and I will repair it. I don't want to impair your own velocity because of something you don't actively use.
