### ISSUE TITLE
Sometimes blocks when launched via NickelMenu

### ISSUE THREAD

**Issue by baskerville** [baskerville/plato#117]
I've tried launching *Plato* via *NickelMenu* using the following entry:
```
menu_item  :main  :Start Plato      :cmd_spawn  :quiet:/usr/local/Plato/plato.sh
```
And it sometimes results in *Plato* blocking (for a minute or so) [on this line](https://github.com/baskerville/plato/blob/9e14eb4502aa0779e5d609882ca37eb719b9dea8/src/library.rs#L39)! What blocks in `load_json` is [the second line](https://github.com/baskerville/plato/blob/9e14eb4502aa0779e5d609882ca37eb719b9dea8/src/helpers.rs#L66).

**Comment by geek1011** [comment]
Can you try using `strace` on Plato?

Also, does this also happen if you use cmd_output and `&` to background Plato?

**Comment by baskerville** [comment]
Here's the relevant excerpt from the output of `strace`:
```
open("/mnt/onboard/books/.metadata.json", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 5</mnt/onboard/books/.metadata.json> <0.000>
read(5</mnt/onboard/books/.metadata.json>, "{", 1) = 1 <0.000>
getrandom(NULL, 0, GRND_NONBLOCK)       = -1 ENOSYS (Function not implemented) <0.000>
open("/dev/random", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6</dev/random> <0.000>
ioctl(6</dev/random>, FIOCLEX)          = 0 <0.000>
poll([{fd=6</dev/random>, events=POLLIN}], 1, -1) = 1 ([{fd=6, revents=POLLIN}]) <172.034>
close(6</dev/random>)                   = 0 <0.000>
open("/dev/urandom", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6</dev/urandom> <0.000>
ioctl(6</dev/urandom>, FIOCLEX)         = 0 <0.000>
read(6</dev/urandom>, "\342\2367\240\370\334D\372\323\306\243\33\324n\312\"p\201Y\206\267\2456i-\314\27D^\1\320r", 32) = 32 <0.000>
read(5</mnt/onboard/books/.metadata.json>, "\n", 1) = 1 <0.000>
read(5</mnt/onboard/books/.metadata.json>, " ", 1) = 1 <0.000>
read(5</mnt/onboard/books/.metadata.json>, " ", 1) = 1 <0.000>
read(5</mnt/onboard/books/.metadata.json>, "\"", 1) = 1 <0.000>
read(5</mnt/onboard/books/.metadata.json>, "5", 1) = 1 <0.000>
read(5</mnt/onboard/books/.metadata.json>, "0", 1) = 1 <0.000>
read(5</mnt/onboard/books/.metadata.json>, "9", 1) = 1 <0.000>
```
The call that blocks is `poll([{fd=6</dev/random>, events=POLLIN}], 1, -1)`. It seems to be blocking for 172 seconds!

**Comment by geek1011** [comment]
That seems to be blocking due to low entropy before falling back to weaker random numbers. How long have you booted for? Also, can you record the value of /proc/sys/kernel/random/entropy_avail every second or so starting from right after Nickel's launch?

Although, I wonder what's needing truly random numbers in Plato...

**Comment by baskerville** [comment]
> Although, I wonder what's needing truly random numbers in Plato... I suspect it's another thread doing it rather than the JSON parser.

I'm afraid it might be the [fancy hasher](https://github.com/shepmaster/twox-hash) I'm using for the DB's hash map.

**Comment by geek1011** [comment]
So probably shepmaster/twox-hash#13.

**Comment by NiLuJe** [comment]
`/dev/random` is apparently quirky (possibly especially on older devices).

I've had to neuter an OpenSSL feature after a similar issue: https://github.com/koreader/koreader-base/pull/1099

**Comment by baskerville** [comment]
I thought it wasn't worth reporting a bug, since the trace is clearly reflecting [the behavior of the `getrandom` crate](https://github.com/rust-random/getrandom/blob/0ad1c7721455b644a775bb4647806ab631250c14/src/lib.rs#L15).

The fact that the function might block is [also acknowledged](https://github.com/rust-random/getrandom/blob/0ad1c7721455b644a775bb4647806ab631250c14/src/lib.rs#L272).

I've decided, as consequence, to replace things that might directly or indirectly depend on `OsRng`, so as to never poll `/dev/random`.

**Comment by NiLuJe** [comment]
Yeah, I'm no expert, but what's surprising is the *amount* of time it can block, and the fact that it does so long after the early boot.

Might be worse just after a resume from suspend?

**Comment by geek1011** [comment]
Well, on most devices there are more sources of entropy, but the Kobo is pretty bare-bones. And, the lib does use GRND_NONBLOCK (and from a quick look, would fall back to pseudo random numbers afterwards), but that's only supported on 3.14+, so it falls back to a blocking random read.
