### ISSUE TITLE
Can't escape Sketch application, no clear instructions

### ISSUE THREAD

**Issue by nanoni17728** [baskerville/plato#132]
Hi, first of all thanks for the hard work!

I just got my Kobo and got Plato installed. I got into the Sketch app but I can't find a way to escape it either by myself or by skimming the documentation. I think those kind of behaviours should be either really explicit or really easy to find just by a quick glance at your repository.

Related to this issue is the usability of your software. Discovering what it is about, how it works and what is available to us is a real pain point and if it wasn't for the engineering quality I would have dropped the ball already. I'm available if you need someone to write a bit of documentation or design/talk about some UX/UI elements.

**Comment by nanoni17728** [comment]
Update: I finally found my way around.

Continuing on what I wrote I think this is a good example of an usability problem. You can find bellow a picture of the 3 dots pop-up menu. You can notice on the picture the size of the dots on the display are roughly the size of the dots you can see on the paper behind.

![photo_2020-08-24_14-57-25](https://user-images.githubusercontent.com/37584624/91047560-8e59a800-e61a-11ea-912d-c3802311da3f.jpg)

For reference, the dots on the paper are around half a millimeter of diameter. I also attached a more zoomed out picture showing the whole screen. You can see what I drew, plus the amount of gestures I had to try before being able to actually exit the application. 

If you didn't previously know there was a menu button and where it's located, I think it's fair to say that you can't see it at all at a quick and a less quick glance. (just get a look at the timestamp between those two posts)

If you ever want to make your software usable for other people and not just the contributors, I think you should look into tweaking those kind of interface elements.

![photo_2020-08-24_14-56-22](https://user-images.githubusercontent.com/37584624/91047502-73873380-e61a-11ea-8891-febff7c6e3d7.jpg)

**Comment by baskerville** [comment]
You're right about the menu icon being too discreet.

I haven't written any documentation regarding *Sketch* yet, sorry about that.

> I'm available if you need someone to write a bit of documentation or design/talk about some UX/UI elements.

Yes, I'm interested: feel free to create an issue to review all the UI problems you might encounter.

**Comment by nanoni17728** [comment]
I'll work on that then. I hope I didn't sound too harsh or pesky, I just read back what I wrote and it's not really the tone I had in mind.

Do you have any other mean of communication besides github issues?

**Comment by baskerville** [comment]
> Do you have any other mean of communication besides github issues?

An e-mail address is given on my *GitHub* profile page.
