### ISSUE TITLE
Broken Wi-Fi on FW >= 4.23

### ISSUE THREAD

**Issue by welps** [baskerville/plato#133]
My Forma ran out of battery so I plugged it in, :boom: :bomb: new firmware update, :boom: :bomb: wifi is broken in plato.

`WIFI_MODULE_PATH` and all the other environment variables seem to not exist anymore as `cat /proc/"$(pidof -s nickel)"/environ` returns nothing for me so the `insmod "$WIFI_MODULE_PATH"` call fails.

I looked into this and @NiLuJe provided a fix for this issue for [koreader](https://github.com/koreader/koreader/pull/6522). I pulled those scripts into plato (disable-wifi / enable-wifi / nickel) and they fix the issue. \**edit*\* I had to pull back in the `udhcpc` call in `enable-wifi` as [this is handled separately in koreader](https://github.com/koreader/koreader/blob/37a01100b7a4733ae26871c4d929114aff8ea143/platform/kobo/restore-wifi-async.sh)

I'm not sure how you want to deal with this @baskerville since I'm not sure if it's better to just take the direct fix or use this as an opportunity to get in parity with the koreader versions.

**Comment by NiLuJe** [comment]
As a sidenote, there were other related fixes before and after that PR ;).
