### ISSUE TITLE
No proper way of navigating through bookmarks when document has lots of annotations

### ISSUE THREAD

**Issue by alehresmann** [baskerville/plato#137]
Hello, I have the following issue: I tend to annotate my documents quite a lot. However, this makes bookmarks and the _top left/right corner_ swipe sequences rather useless: if I want to bookmark a few pages and navigate through them, I am limited by my annotations, which essentially turn the _top left/right corner_ swipe sequences into just another _go to previous/next page_. I end up not using bookmarks altogether, and instead use chapters to navigate through the documents, which works, but bookmarking would have been easier.

I wish there was a way of either using these swipe sequences solely for navigating bookmarks, or having a way to browse my bookmarks, much like I'm able to browse the chapters of a document.

**Comment by baskerville** [comment]
> I wish there was a way of either using these swipe sequences solely for navigating bookmarks, or having a way to browse my bookmarks, much like I'm able to browse the chapters of a document.

It would, indeed, be better to have separate shortcuts for bookmarks and annotations. I also agree that a bookmark/annotation browser would be a useful feature.
