### ISSUE TITLE
Documentation for calculator

### ISSUE THREAD

**Issue by siraben** [baskerville/plato#139]
I noticed that there's a screenshot of the calculator in use, however looking around the code there doesn't seem to be documentation on what input the calculator can accept and what it can do. For instance, what does the following declaration of `lab` mean?

```
op a lab b = char 9584 + ? a b rho 2
```

**Comment by baskerville** [comment]
The *Calculator* is a thin wrapper around [ivy](https://github.com/robpike/ivy). One of the special commands you might want to try is `)help`.

**Comment by Eeems** [comment]
> 
> 
> The _Calculator_ is a thin wrapper around [ivy](https://github.com/robpike/ivy). One of the special commands you might want to try is `)help`.

It would probably still be a good idea to link to ivy in your documentation.

**Comment by baskerville** [comment]
Fixed by #140.

The aforementioned example is in fact my own translation, in *ivy*, of a famous *BASIC* one-liner: `10 PRINT CHR$(205.5+RND(1)); : GOTO 10`.
