### ISSUE TITLE
Table of contents doesn’t indicate current chapter

### ISSUE THREAD

**Issue by lpan** [baskerville/plato#145]
It will be nice if we can highlight the current chapter in the Table of Contents view.

For example, when I am on Chapter 5, the TOC doesn't indicate which chapter I'm on.
![image](https://user-images.githubusercontent.com/12106903/103173778-49918800-482b-11eb-9d4a-eef40357e3eb.jpeg)

**Comment by baskerville** [comment]
It should highlight the current chapter.

I'm afraid I won't be able to reproduce without the document and the corresponding reading state.

**Comment by lpan** [comment]
I tried on other documents. And you are right. It seems it is document-specific. :sweat_smile:

**Comment by baskerville** [comment]
It would be great if you could send me the document privately.

**Comment by lpan** [comment]
Still having the same issue with that document after upgrading to 0.9.11 :cry: 

@baskerville I am going to send the document to you privately. Thanks!

**Comment by lpan** [comment]
Thanks for the fix @baskerville
