### ISSUE TITLE
PDF reading settings seem incomplete

### ISSUE THREAD

**Issue by RhvdG** [baskerville/plato#153]
Comparing Plato to Koreader, and finding it more pretty and faster, I was dismayed to see that PDF reading is near-impossible like it is with the regular Kobo software. Scrolling through the PDF using the width of the reader screen is not an option, it seems. I can crop the pages, but that means simply losing much content. Am I overlooking something? I did notice that the rightmost icon on the tool bar below (that looks like a bullet list with indents) doesn't do anything, except make the toolbar disappear. Perhaps the much needed options for PDF viewing are hidden there/ But I can't access them. I'd like to use Plato over Koreader, for aesthetic reasons and because browsing through my library is a pain on Koreader — but I need easily readable PDFs!

PLEASE DISREGARD: I figured it out. Perhaps the manual should mention tapping the title to set the zoom. I miss books I paid for (probably unavoidable) and would like to see reading statistics. And gaps between the pages of a PDF. But overall I am truly impressed! Plato is amazing.

I do have some questions that aren't answered in the manual or elsewhere. Is this a good place to ask them?

**Comment by baskerville** [comment]
> Perhaps the manual should mention tapping the title to set the zoom.

The manual mention that the title is tappable: *Tap the title label to bring up the book menu*. It also mention the other way of setting the zoom mode: *Spread (resp. pinch) horizontally to switch the zoom mode to fit-to-width (resp. fit-to-page)*.

> I miss books I paid for (probably unavoidable)

What format are you referring to?

> I do have some questions that aren't answered in the manual or elsewhere.

You can ask questions on *Plato*'s [MR thread](https://www.mobileread.com/forums/showthread.php?t=292914).
