### ISSUE TITLE
Plato crashing on mupdf errors that do not prevending overall rendering of the document.

### ISSUE THREAD

**Issue by Kratacoa** [baskerville/plato#154]
Using Plato on Remarkable with [LinusCDE's port](https://github.com/LinusCDE/plato) I have noticed that the reader crashes with the [mupdf error described here](https://bugs.ghostscript.com/show_bug.cgi?id=703379).  
As it is, the error itself has been fixed a few days ago and will be available in the next update of the library.
You can find it alleged to the bug report.  
The error is pretty tame, given that the the document itself renders fine in `mupdf` itself.  
@LinusCDE suggested that I report this, as it may be a use case for the recently implemented "dialogs".  
P.S. Forgive me if it's not good material for an issue, but given that the Discussions page isn't enabled, I wasn't sure how to report this.

**Comment by baskerville** [comment]
Could you share the document that makes it crash?

I've not been able to reproduce with the document attached to the aforementioned MuPDF bug report.

**Comment by LinusCDE** [comment]
The document in the bug report is the very same that I could reproduce it with as well. Below is the error that was output. The error message originates from mupdf and I think there I some code in plato that printed the message (probably as part of an anyhow error?).

I also didn't rebuild the libs but use the download/fast way and the mupdf lib indeed matches the one in the 0.9.13 release to the byte.

![image](https://user-images.githubusercontent.com/22298664/106642942-4ce60500-6589-11eb-9721-cbe6f23a7dd4.png)

I'm not sure why the thread there paniced on a seemingly unrelated note (never had that crash in any other scenario). Sometimes plato seems to crash but sometimes is may also just hang weirdly.

**Comment by Kratacoa** [comment]
> I've not been able to reproduce with the document attached to the aforementioned MuPDF bug report.

Are you using the library as of the latest commit?  
I can't think of anything else (unless mupdf or pdfs are indeterministic 😅), as that's the exact file I've used, and I've only met this error there.

**Comment by baskerville** [comment]
> The error message originates from mupdf and I think there I some code in plato that printed the message (probably as part of an anyhow error?).

No: the error is printed by MuPDF itself and the crash seems unrelated. Is the crash happening with the emulator? If so, you'll get a backtrace with `RUST_BACKTRACE=1 ./run-emulator.sh`.
