### ISSUE TITLE
fast battery discharge even in sleep mode

### ISSUE THREAD

**Issue by bassam-404** [baskerville/plato#157]
Using Plato: 0.9.13 on Kobo Aura One (software version: 4.25.15875), installed with one-click install package

as title, if I forgot Plato on Sleep mode, I'll wake up with empty battery.  While in other readers or everything is fine. Couldn't know why this is happening or  how to pull some logs to help.

**Comment by bosel** [comment]
I have the same experience on Clara using all Plato versions of the last year or so. I would also be willing to provide logs etc. to troubleshoot

**Comment by baskerville** [comment]
Please install the latest version (0.9.16) and provide the [relevant information](https://github.com/baskerville/plato/issues/158#issuecomment-786534383).

**Comment by bosel** [comment]
`<html>
	<head>
		<title>System Info</title>
		<link rel="stylesheet" type="text/css" href="css/sysinfo.css"/>
	</head>
	<body>
		<table>
			<tr>
				<td class="key">Model name</td>
				<td class="value">Clara HD</td>
			</tr>
			<tr>
				<td class="key">Hardware</td>
				<td class="value">Mark 7</td>
			</tr>
			<tr class="sep"></tr>
			<tr>
				<td class="key">Code name</td>
				<td class="value">nova</td>
			</tr>
			<tr>
				<td class="key">Model number</td>
				<td class="value">376</td>
			</tr>
			<tr>
				<td class="key">Firmare version</td>
				<td class="value">4.26.16704</td>
			</tr>
			<tr class="sep"></tr>
			<tr>
				<td>IP Address</td>
				<td>172.10.40.103
</td>
			</tr>
			<tr>
				<td>Storage (Free / Total)</td>
				<td>6.50 G / 6.85 G</td>
			</tr>
			<tr>
				<td>Memory (Free / Total)</td>
				<td>272 M / 497 M</td>
			</tr>
			<tr>
				<td>Load Average</td>
				<td>4.6% 24.6% 13.8%</td>
			</tr>
			<tr class="sep"></tr>
			<tr>
				<td>CPU</td>
				<td>mx6sll</td>
			</tr>
			<tr>
				<td>PCB</td>
				<td>E60K00</td>
			</tr>
			<tr>
				<td>DisplayPanel</td>
				<td>6" Bottom EPD</td>
			</tr>
			<tr>
				<td>DisplayCtrl</td>
				<td>MX6SLL+TPS65185</td>
			</tr>
			<tr>
				<td>DisplayBusWidth</td>
				<td>8Bits</td>
			</tr>
			<tr>
				<td>DisplayResolution</td>
				<td>1448x1072</td>
			</tr>
			<tr>
				<td>FrontLight</td>
				<td>TABLE0</td>
			</tr>
			<tr>
				<td>FrontLight_LEDrv</td>
				<td>LM3630</td>
			</tr>
			<tr>
				<td>FL_PWM</td>
				<td>LM3630</td>
			</tr>
			<tr>
				<td>TouchCtrl</td>
				<td>CYTT21X</td>
			</tr>
			<tr>
				<td>TouchType</td>
				<td>C-Type</td>
			</tr>
			<tr>
				<td>Battery</td>
				<td>PR-284983N-1500mA</td>
			</tr>
			<tr>
				<td>IFlash</td>
				<td>Micro SD</td>
			</tr>
			<tr>
				<td>RamSize</td>
				<td>512MB</td>
			</tr>
			<tr>
				<td>LightSensor</td>
				<td>No</td>
			</tr>
			<tr>
				<td>HallSensor</td>
				<td>TLE4913</td>
			</tr>
			<tr>
				<td>RSensor</td>
				<td>No</td>
			</tr>
			<tr>
				<td>Wifi</td>
				<td>RTL8189</td>
			</tr>
		</table>
	</body>
</html>
`

**Comment by baskerville** [comment]
You forgot `info.log`. Try disabling the WiFi and see if it helps.

**Comment by bosel** [comment]
[trace.txt](https://github.com/baskerville/plato/files/6103060/trace.txt)

**Comment by bosel** [comment]
[info.log](https://github.com/baskerville/plato/files/6103088/info.log)

**Comment by bassam-404** [comment]
with Plato 0.9.16 and after several days of testing, everything is working good. No weird battery behavior till now.

**Comment by bosel** [comment]
This can probably be closed. The clean install I did to obtain a trace seems to have solved this issue for me as well.
