### ISSUE TITLE
Porting to Remarkable

### ISSUE THREAD

**Issue by darvin** [baskerville/plato#16]
Hello!

I wanna port your reader to Remarkable tablet. We got a full functional RUST toolchain:

https://github.com/rampantmonkey/remarkable.rs

(default pdf viewer is hella slow)
Got any caveats/recommendations/advice before I dig in?

**Comment by baskerville** [comment]
Interesting initiative.

Porting it shouldn't be too hard: you'll have to adapt `input.rs` and `device.rs`.

And write an implementation for the `FrameBuffer` trait.

The `View` trait mostly depends on `Event` and `FrameBuffer`.

**Comment by baskerville** [comment]
Yes, it might be worth trying to untangle the modules.

**Comment by darvin** [comment]
Current status of port: framebuffer is working (im using libremarkable, but after reading their code im thinking about trying to drop them and try to fit into your framebuffer implementation if possible), input is working with minimal hacks.

Do you have .metadata.json? ive got no Kobo reader, its a file generated by their default reader, right?..
https://www.youtube.com/watch?v=mdjYLx0p7b0&feature=youtu.be

**Comment by darvin** [comment]
next:
 * checking if it actually reads stuff (i would appreciate a sample of `.metadata.json`)
 * hardware buttons
 * figure out why framebuffer is so ugly
 * battery

**Comment by baskerville** [comment]
> Checking if it actually reads stuff (I would appreciate a sample of .metadata.json)

You need to put some documents somewhere on your device and set *libraryPath* in `settings.json` to the full path of the aforementioned directory.

> Hardware buttons

You need to add the corresponding key codes and button codes in `input.rs` (cf. [Reading-Physical-Buttons.md](https://github.com/rampantmonkey/remarkable.rs/blob/master/wiki/Reading-Physical-Buttons.md)) and also fill out `ButtonCode::from_raw`. Don't forget to pass all the relevant pseudo files (`/dev/input/event{0-2}`) to `raw_events` (the *Kobo* devices only have `event0` and `event1`).

> Figure out why framebuffer is so ugly

It seems like you might be using inappropriate update modes.

You could try taking a screenshot.

Regarding the touch layer: you might need `proto: TouchProto::MultiB` in your device definition.

> Battery

You just need to implement the `Battery` trait.

**Comment by baskerville** [comment]
Regarding the framebuffer: I thought that there might also be a problem with your implementation of the `wait` function: the value of `MXCFB_WAIT_FOR_UPDATE_COMPLETE` is probably not the same on the *reMarkable*: the *mxcfb* ioctl calls seem to [differ slightly](https://github.com/rampantmonkey/remarkable.rs/blob/ca8ff05d1d5c96ce735b83d9e5f7cc3e9f2dda39/src/refresh.rs#L100).

**Comment by baskerville** [comment]
`MXCFB_SEND_UPDATE` is also probably wrong because the *reMarkable* uses a different `MxcfbUpdateData` struct.

It might be better to rely on the `ioctl-gen` package:

```rust
const MXCFB_SEND_UPDATE: libc::c_ulong = iow!(b'F', 0x2E, std::mem::size_of::<MxcfbUpdateData>()) as libc::c_ulong;
```

Don't forget to fix the structs.

**Comment by darvin** [comment]
@baskerville Thanks! looking into that.

was able to list the pdfs. every time i tap on them tho instead of jumping to pdf context menu pops up: `Add Category` / `Remove`. On the right spot tho. Whats up with that?

**Comment by baskerville** [comment]
> Every time I tap on them tho instead of jumping to PDF context menu pops up: `Add Category` / `Remove`.

If you've tried every multitouch protocol (`TouchProto::Multi{A,B}`) in your device definition, then you'll have to provide debug outputs for me to understand the protocol:

Insert the following:
```rust
println!("{:.6} {} {} {}", seconds(evt.time), evt.kind, evt.code, evt.value);
```
At the beginning of the loop in `parse_device_events`.

Redirect *Plato*'s outputs to a file.

What you need to record is a single tap and a two-finger swipe.

**Comment by baskerville** [comment]
Here's a [patch](https://gist.github.com/baskerville/7527596b1ac14cb98023155ba7c65669).

**Comment by darvin** [comment]
patch helped!

opened a pull request to prepare for upstream:
https://github.com/baskerville/plato/pull/17
