### ISSUE TITLE
[Feature] Copy To and Rename file

### ISSUE THREAD

**Issue by Mavireck** [baskerville/plato#162]
Hi baskerville and thank you for Plato which I have been using for about 3 years now ;-)
I mostly use if to read pdfs and sheet music, and therefore I do have a little feature request that would make my life a lot easier:

**Would it be possible to add the option to copy a file to another librairy (and not only move it) in the context menu which appears after long-pressing on a file ?**

Use case scenario : 
I have a large (1000+) librairy of sheet music. When I play with friends, I like to have a "setlist" : a folder with only the music we are going to play. For now, when I know in advance what we will play, I create the setlist on my computer (by copying the corresponding files to a specific librairy called "setlist"), but I do not always have access to a computer. So I would appreciate being able to create that setlist _directly from plato_, by searching and copying the files to that setlist, without removing them from the original librairy.

If you do not have time, then don't do it, I have been working like that for 2 years, I can continue that way ;-)
Thank you a lot !

(I am also quite afraid to do a push request, because I am afraid my implementation would not be coherent with the way you code)

**Comment by baskerville** [comment]
It seems reasonable.

The title of this issue also mentions *Rename file*?

**Comment by Mavireck** [comment]
Thank you a lot !

Yes I mentionned file renaming, and I forgot to detail it on my first message. I think it would be useful too, especially for my setlist, since I can then rename the file from xxxx.pdf to 1-xxxx.pdf for instance, and then sorting by name, so that they appear in the order I want.

Another scenario where this would be useful is when you download a file from Kobo's webbrowser (since you cannot choose the file's name): after some time the kobo's storage can become quite a mess if I do not rename these files.

**Comment by baskerville** [comment]
This was implemented in fb45bb0a761424eb022b161af31bff8591c5993f and 6a4e0e5cc68ffdd6f528e04a493a7e3a1733e846.
