### ISSUE TITLE
Epub highlighting with Bookerly font glitched

### ISSUE THREAD

**Issue by LinusCDE** [baskerville/plato#163]
This is more a minor issue. Highlighting is bugged when using the bookerly font.

Using an ebook with font size 10.5, default spacing (1.2 em) and default margin (8 mm). The font used is Bookerly though (extracted from the kindle apk).

When highlighting this area:

![1](https://user-images.githubusercontent.com/22298664/115306677-782fc780-a168-11eb-8a0a-25e33edbd6fa.png)

It results in this preview:

![2](https://user-images.githubusercontent.com/22298664/115306938-d2308d00-a168-11eb-8061-2f78999c3f85.png)

and this final highlight:

![3](https://user-images.githubusercontent.com/22298664/115306975-dd83b880-a168-11eb-9ca6-98b969fc1a98.png)

It works fine if the highlighted area does not use two lines on screen. I guess there is some calculation problem. Not sure if the fault is bookerly of whatever font library is used for rendering. Just a minor thing though since not many use the font anyway. Maybe other fonts could be bugged like this as well though.

---

P.S.: Keep up the great work. :+1: Just merged in the 0.9.14 to 0.9.16 for the reMarkable port ([release](https://github.com/LinusCDE/plato/releases/tag/0.9.16-rm-release-8), [package](https://github.com/toltec-dev/toltec/pull/344)). For the package I re-built the migrate_hex-keys script to use bash and jq [here](https://github.com/toltec-dev/toltec/blob/5c227225e17f8064f5696bebc1d0d3cc3419c784/package/plato/package#L89).

**Comment by baskerville** [comment]
Can you reproduce with other *EPUB* (using the same font)?

What's the corresponding `annotations` array in `.reading-states/<BOOK_ID>.json`?

**Comment by baskerville** [comment]
I was able to reproduce. It happens each time the highlight rectangle of one line intersects with the highlight rectangle of the following line. The font used isn't the source of the problem since an overlap can be cancelled by increasing the line height (or provoked by decreasing it).

**Comment by baskerville** [comment]
> Changing the line spacing from 1.2em to 2em doesn't change the spacing at all for me.

This only changes the default line height. If the style sheets define a line height, then it won't work.

> Making the font bigger also doesn't fix it

It shouldn't.

> (not sure what was meant by line height).

I meant *the vertical distance of the base lines of consecutive lines in a paragraph*,  also known as *line height* or *leading*.

**Comment by baskerville** [comment]
Thanks for the report.
