### ISSUE TITLE
Keep page break in fit-to-width mode

### ISSUE THREAD

**Issue by belotv** [baskerville/plato#173]
Hello,

This software is really nice on my new Kobo Libra H2O, thank you very much for the hard work. I am reading technical PDFs, and I mainly use landscape mode in fit-to-width mode, so pages get divided in 3.

However the last part of the page always get merged with the beginning of the next one, which make the document difficult to read. I would prefer the last part to be filled with blank space, and to have the next page starting at the beginning of the next screen.

Is there any way to keep page breaks ?

**Comment by paulrouget** [comment]
Dupe: #252
