### ISSUE TITLE
Charging LED doesn't turn on/off (and can stay lit when later unplugged)

### ISSUE THREAD

**Issue by cpick** [baskerville/plato#175]
If my Kobo is charging (with the charging indicator light/LED lit) when I start Plato (via NickelMenu) then the charging LED will remain lit even after I later unplug the USB cable.  Additionally, Plato's battery icon on the top bar will keep displaying the plug image even after the cable is unplugged (the battery drop-down does correctly change its text from "Charging 90%" to "Discharging 90%, however).

If I then plug it in again the plug image will be correctly removed from the batter icon when I unplug it a second time.  (The charging LED remains lit through any number of plug+unplug cycles.)  If I quit Plato (using the top-right menu) while it's unplugged, then Nickel turns off the charging LED as soon as it loads again.

If I start Plato with the Kobo unplugged, then plugging it in does not light up the charging LED.  (The battery icon on the top bar works properly, though.)

I don't care too much whether Plato turns the charging LED turns on and off when (un)plugged, but I believe leaving it on even when I had unplugged drained my battery faster than I was used to.  Perhaps just always turning off the LED when starting Plato would be a reasonable choice?

I have "Indicator light while charging" set to "On" in Nickel's "Energy saving and privacy" settings.
This is on a Kobo Clara HD (model N249) running 4.26.16704 and Plato 0.9.17.

**Comment by baskerville** [comment]
> Additionally, Plato's battery icon on the top bar will keep displaying the plug image even after the cable is unplugged (the battery drop-down does correctly change its text from "Charging 90%" to "Discharging 90%, however).

I've never experienced that, but I always start *Plato* using the [standalone method](https://github.com/baskerville/plato/blob/master/contrib/firmware.patch).

> I don't care too much whether Plato turns the charging LED turns on and off when (un)plugged, but I believe leaving it on even when I had unplugged drained my battery faster than I was used to. Perhaps just always turning off the LED when starting Plato would be a reasonable choice?

I guess we could [turn off the LED](https://github.com/baskerville/plato/blob/2911f9c0b4f032b7611c2b3f9a3cb4e36b32691e/contrib/plato.sh#L21-L26) in all cases.

**Comment by cpick** [comment]
> I guess we could [turn off the LED](https://github.com/baskerville/plato/blob/2911f9c0b4f032b7611c2b3f9a3cb4e36b32691e/contrib/plato.sh#L21-L26) in all cases.

That suggestion worked great.  With the patch from #176 applied:
* Starting in Nickel while charging (with the LED on) and then launching Plato will turn off the LED
* Quitting Plato while charging will cause Nickel to turn the LED back on

**Comment by baskerville** [comment]
> Plato's battery icon on the top bar will keep displaying the plug image even after the cable is unplugged

Maybe the pseudo-file for the battery's capacity hasn't updated yet when the unplug event is received from `/tmp/nickel-hardware-status`?
