### ISSUE TITLE
embedded style not applied in plato?

### ISSUE THREAD

**Issue by termac** [baskerville/plato#182]
When rendering code snippets from an epub the embedded style seems to not be applied. This is how it looks in koreader vs. plato for me:

![code](https://user-images.githubusercontent.com/552045/124962130-8df1b200-e01e-11eb-9761-5648fc387832.png)

I am very new to ereaders & epubs, so I apologize if it is just me being stupid and I would appreciate some pointers on how to get the nice formatting working with plato.

**Comment by baskerville** [comment]
I guess it might be due to the limited capabilities of *Plato*'s CSS engine. You'd need to provide an EPUB document (privately if needed) for me to investigate further.

**Comment by termac** [comment]
I will send a link in a PM.
I got the emulator up and running and would like to poke around a bit myself too, what would be the best way to go about it in this case? Is there an easy way to enable some logging or would I use a debugger to stop when the css is applied?

**Comment by baskerville** [comment]
The style sheet uses unsupported selectors: `a b`. *Plato* only supports `a > b` and `a + b`.
