### ISSUE TITLE
O'Reilly epubs are all rendered with italicised fonts

### ISSUE THREAD

**Issue by daenney** [baskerville/plato#183]
Alright, this is a bit of a weird one... but. All my O'Reilly books are rendered with an italicised font and I don't quite get why. With the exception of chapter titles/headings, everything else (including code samples) is rendered as if italics were turned on.

I'm assuming there's actually something in the EPUB document that causes this, but it is unique to Plato. The default Kobo Reader and koreader don't seem to do this for the same set of documents. I figured it might be some interaction with the Libertinus Serif font, but despite the fact that I have other fonts installed I'm not give the option to pick a different font (only LIbertinus Serif shows up in the list).

I also specifically mention O'Reilly because I can only reproduce it with their books (legitimate copies through ebooks.com), whereas other books in EPUB format on the same device don't exhibit this property.

My version of plato is 0.9.17, on a Kobo Libra H2O using firmware version 4.26.16704

```
$ pwd
/run/media/daenney/KOBOeReader/.adds/plato
```
```
$ tree fonts/
fonts/
├── Cormorant-Regular.ttf
├── Delius-Regular.ttf
├── LibertinusSerif-BoldItalic.otf
├── LibertinusSerif-Bold.otf
├── LibertinusSerif-Italic.otf
├── LibertinusSerif-Regular.otf
├── NotoSans-BoldItalic.ttf
├── NotoSans-Bold.ttf
├── NotoSans-Italic.ttf
├── NotoSans-Regular.ttf
├── NotoSerif-BoldItalic.ttf
├── NotoSerif-Bold.ttf
├── NotoSerif-Italic.ttf
├── NotoSerif-Regular.ttf
├── Parisienne-Regular.ttf
├── SourceCodeVariable-Italic.otf
├── SourceCodeVariable-Roman.otf
└── VarelaRound-Regular.ttf

0 directories, 18 files
```

```
$ cat Settings.toml 
selected-library = 0
keyboard-layout = "English"
frontlight = true
wifi = false
sleep-cover = true
auto-share = false
button-scheme = "natural"
auto-suspend = 30
auto-power-off = 3
time-format = "%H:%M"
date-format = "%A, %B %-d, %Y"

[[libraries]]
name = "On Board"
path = "/mnt/onboard"
mode = "database"
sort-method = "added"
first-column = "title-and-author"
second-column = "progress"
thumbnail-previews = true

[[libraries.hooks]]
path = "Articles"
program = "bin/article_fetcher/article_fetcher"
sort-method = "added"
first-column = "title-and-author"
second-column = "progress"

[[libraries]]
name = "Removable"
path = "/mnt/sd"
mode = "database"
sort-method = "opened"
first-column = "title-and-author"
second-column = "progress"
thumbnail-previews = true

[intermissions]
suspend = "logo:"
power-off = "logo:"
share = "logo:"

[[frontlight-presets]]
timestamp = 634

[frontlight-presets.frontlightLevels]
intensity = 40.022804
warmth = 21.892817

[[frontlight-presets]]
timestamp = 634

[frontlight-presets.frontlightLevels]
intensity = 40.022804
warmth = 21.892817

[[frontlight-presets]]
timestamp = 643

[frontlight-presets.frontlightLevels]
intensity = 40.022804
warmth = 43.329533

[home]
address-bar = false
navigation-bar = true
max-levels = 3
max-trash-size = 33554432

[reader]
finished = "close"
south-east-corner = "go-to-page"
strip-width = 0.6
corner-width = 0.4
font-path = "/mnt/onboard/fonts"
font-family = "Libertinus Serif"
font-size = 11.0
text-align = "left"
margin-width = 8
line-height = 1.2
dithered-kinds = ["jpeg", "jpg", "png", "cbz"]

[reader.paragraph-breaker]
hyphen-penalty = 50
stretch-tolerance = 1.26

[reader.refresh-rate]
regular = 8
inverted = 2

[import]
unshare-trigger = true
startup-trigger = true
extract-epub-metadata = true
allowed-kinds = ["oxps", "epub", "xps", "cbz", "djvu", "pdf", "fb2"]

[dictionary]
margin-width = 4
font-size = 11.0

[sketch]
save-path = "Sketches"
notify-success = true

[sketch.pen]
size = 2
dynamic = true
color = 0
min-speed = 35.43307
max-speed = 1800.0

[calculator]
font-size = 8.0
margin-width = 2
history-size = 4096

[battery]
warn = 10.0
power-off = 3.0

[frontlight-levels]
intensity = 40.022804
warmth = 43.329533
```

(As an aside, thanks so much for Plato. It is, ironically, the only reader I can use on my Kobo to read Programming Rust. Both the default reader and koreader have extreme issues with it but Plato is flawless).

**Comment by baskerville** [comment]
I'm afraid the underlying problem might be the same as in #182.

Could you privately provide one of the problematic documents?

**Comment by daenney** [comment]
I'm not super comfortable sharing the ebook, but if it works for you I'm happy to sponsor a gift card for ebooks.com instead so you can buy your own copy? In my case I'm running into this reading Programming Rust, 2nd Edition. Idk if that one would be useful to you, but I'm pretty sure you can buy any recent book from O'Reilly there and replicate the issue.

**Comment by daenney** [comment]
Alright. If you do want a copy to replicate it, I'm honestly happy to sponsor it. Plato's well worth it from my point of view.

**Comment by baskerville** [comment]
Have you tried *Plato* 0.9.18?

**Comment by daenney** [comment]
Thanks for the nudge; I wasn't watching for releases so had completely missed this. I just updated and 0.9.18 does indeed fix it. Things are rendered as expected now, no more italics
