### ISSUE TITLE
[feature] exctarct PDF metadata

### ISSUE THREAD

**Issue by wakamesh** [baskerville/plato#186]
It would be nice if in the `title-and-author` view we could see the title and author of each PDF, not the file name.

**Comment by baskerville** [comment]
I could add an option to extract the metadata from PDF. The reason I haven't done so is that almost all of the PDF I've encountered contained useless metadata.

**Comment by wakamesh** [comment]
But now quite a few journal article PDFs contain their authors and titles as metadata.
Personally I add metadata manually since the default software supports them.  This feature helps people switch from the stock reader.

**Comment by baskerville** [comment]
I'll add an option then.
