### ISSUE TITLE
Unable to view document (includes test)

### ISSUE THREAD

**Issue by skinkie** [baskerville/plato#193]
The attached epub results in an empty page.

[test.zip](https://github.com/baskerville/plato/files/7110708/test.zip)

**Comment by baskerville** [comment]
Thanks for the report.

It has to do with some of the selectors (e.g. `nav[epub|type~="landmarks"]`) present in the included style sheets.

**Comment by skinkie** [comment]
> Thanks for the report.
> 
> It has to do with some of the selectors (e.g. `nav[epub|type~="landmarks"]`) present in the included style sheets.

Is this 'invalid' css? I remember that I saw before that the blitz.css was reporting issues, but did not realise that could have been the cause of this issue. Yesterday I have seen the most mysterious issues on the stock viewer for the lack of inheritance of properties, so I am not very surprised it is actually a css issue _again_.

**Comment by baskerville** [comment]
> Is this 'invalid' css?

I also wasn't aware of this syntax but it [actually exists](https://www.w3.org/TR/selectors-3/#typenmsp) in CSS3.

**Comment by skinkie** [comment]
Is there an option on reporting the CSS handling failed, gracefully ignore such events, or log them for the expert user?

**Comment by aussetg** [comment]
It breaks all of Standard Ebooks (standardebooks.org/) Advanced Epubs by the way :)
