### ISSUE TITLE
Rakuten/Kobo sync books don't show up

### ISSUE THREAD

**Issue by daenney** [baskerville/plato#197]
When I sync books purchased from Rakuten/Kobo they don't show up in Plato (though they show up on the regular launcher).

I suspect as much would happen, since the books aren't directly available in the root of the storage.

Looking at timestamps after a sync with a new book, they seem to end up in `.kobo/kepub`:

```
-rw-r--r-- 1 daenney 1.6M Sep 21  2021 224b1ad5-94b7-4419-bd4d-437f17b7f3e4
-rw-r--r-- 1 daenney 594K Sep 21  2021 25aa7c6f-1def-484a-a00a-25ad40c7c0f9
-rw-r--r-- 1 daenney 3.8M Jul 18 00:52 58832f8b-1739-48fc-9200-6cc10435ce5f
-rw-r--r-- 1 daenney 752K Sep 21  2021 95ae8f78-7042-4398-825d-3d9a28e94b8a
-rw-r--r-- 1 daenney  38K Jul 18 00:52 9f452824-c8fb-46d3-aefe-02a8c2d29ef2
-rw-r--r-- 1 daenney 3.1M Sep 21  2021 a4409a6a-623c-4b96-900d-ddcaf2e11947
-rw-r--r-- 1 daenney 1.9M Jul 18 00:52 a44cea4e-c4f2-4aec-baac-9a4bb8bc234b
-rw-r--r-- 1 daenney  12M Sep 21 14:06 a5e01062-2441-4b7c-aa40-33fde8de49d3
-rw-r--r-- 1 daenney 3.1M Jul 18 00:52 c0289a5a-de6a-4283-bba9-549b45abfd59
-rw-r--r-- 1 daenney 1.8M May 10 19:40 de0d843e-7b54-4505-9213-0ecf1866322a
-rw-r--r-- 1 daenney  54K Sep 21  2021 f9f8ca84-0aa7-4ded-8cb2-55ac79956980
```

According to `file`, these are all EPUB documents, though I can't open a single one with Zathura (using the mupdf plugin).

Based on my understanding I'm guessing there's some Kobo DRM involved here, and these things need to be decrypted somehow?

**Comment by daenney** [comment]
Seems to be Adobe Digital Editions for the DRM.

**Comment by baskerville** [comment]
> When I sync books purchased from Rakuten/Kobo they don't show up in Plato (though they show up on the regular launcher).
> 
> I suspect as much would happen, since the books aren't directly available in the root of the storage.
>
> Looking at timestamps after a sync with a new book, they seem to end up in `.kobo/kepub`.

*Plato* searches recursively within a library's path, but skips hidden directories.

You'd have to add a library :

```toml
[[libraries]]
name = "Kobo ePub"
path = "/mnt/onboard/.kobo/kepub"
```

> According to `file`, these are all EPUB documents, though I can't open a single one with Zathura (using the mupdf plugin).

*MuPDF* just ignores DRM-protected EPUB documents.

> Based on my understanding, I'm guessing there's some Kobo DRM involved here, and these things need to be decrypted somehow?

From my experience, only the fonts are encrypted. But *Plato* ignores the document's fonts, so it shouldn't be necessary.

The only thing missing on *Plato*'s side is a fallback for guessing the type of extension-less files.
