### ISSUE TITLE
Installation is broken

### ISSUE THREAD

**Issue by leeuwerck** [baskerville/plato#198]
Hi,

First I want to thank you for this wonderful piece of software.

After following the one-click install instructions (https://www.mobileread.com/forums/showthread.php?t=314220) some months ago, I've used Plato on my Kobo Aura H2O Edition 2 without issue. But yesterday, the NickelMenu started to show a "Generator error" when pressed. I've tried reinstalling the most recent version of the one-click zip, to no avail. I don't know if an automatic update of the firmware caused the issue. Automatic updates were enabled, as they are by default.

The firmware version is 4.28.18220

What can I do to use Plato again?

**Comment by baskerville** [comment]
@pgaskin or @NiLuJe might have some insights.

**Comment by leeuwerck** [comment]
Thanks for the help guys! I hadn’t correctly copied the content of the zip file to the root of my Kobo directory. Now it works again.
