### ISSUE TITLE
Frontlight color formulas are incorrect for Aura One

### ISSUE THREAD

**Issue by occivink** [baskerville/plato#200]
I've posted about the issue on the [mobileread](https://www.mobileread.com/forums/showpost.php?p=4161475&postcount=737) forum, but figured that this is a better place to keep track of the issue.

Judging by the [implementation](https://github.com/baskerville/plato/blob/master/src/frontlight/natural.rs#L108-L115), the red LEDs still have a value of 27%, even when `warmth == 0.0`. I don't know if the fix is as simple as setting `red = 0` when `w == 0.0`, as the formula is a bit opaque to me.

Anyway since I have no interest in the 'warmth' feature I've disabled it with this patch which works well. With this, only the white LEDs are turned on.

```diff
diff --git a/src/frontlight/natural.rs b/src/frontlight/natural.rs
index 5f0f5b8..da2fc35 100644
--- a/src/frontlight/natural.rs
+++ b/src/frontlight/natural.rs
@@ -111,8 +111,8 @@ impl NaturalFrontlight {
             } else {
                 green + 20.0 + 7.0 * (1.0 - green / 64.0) + w * 4.0
             };
-            self.set(LightColor::Red, red);
-            self.set(LightColor::Green, green);
+            self.set(LightColor::Red, 0.0);
+            self.set(LightColor::Green, 0.0);
         } else {
             let orange = 95.0 * (w * i).sqrt();
             self.set(LightColor::Orange, orange);
```

edit: also, it looks like the white LEDs can only be set to 80% of their max value?

**Comment by baskerville** [comment]
I've [explained the current formula](https://github.com/koreader/koreader/issues/2321#issuecomment-354672006) a while ago.
