### ISSUE TITLE
How to Zoom? I can't seem to make it work

### ISSUE THREAD

**Issue by vinoff** [baskerville/plato#201]
I have a Kobo Clara HD and I am running latest released plato.

I am on a kepub file and I am trying to zoom on a map. I tried spreading diagonally, horizontally, vertically. I tried tapping, I tried holding, I tried many things. How is one supposed to zoom? I read the Manual but it doesn't seem to work?

Sorry in advance for my naivety.

**Comment by tootbrute** [comment]
I'm also running Plato on a Kobo Clara HD 0.9.19. I can't figure out how to zoom either.
I can't find any Custom setting in the Settings.toml file.
I tried lots of different things: single press, long press, pinching but can't seem to zoom into maps in an epub.

Is there a setting I need to enable somewhere?
