### ISSUE TITLE
Invert previous/next page tap region

### ISSUE THREAD

**Issue by occivink** [baskerville/plato#214]
Hi,
It would be nice to have a setting to invert the east and west region tap functionality (respectively next and previous page).
I usually hold my kobo with my left hand and use my thumb to go to the next page. I currently use the swipe gesture, but it's not as comfortable as a single tap. 

For what it's worth, such a setting exists in Nickel

**Comment by baskerville** [comment]
As of fff5ee4, you can achieve your goal by making the following adjustments in the `[reader]` section of *Settings.toml*:
```toml
west-strip = "next-page"
east-strip = "previous-page"
```

**Comment by occivink** [comment]
Much appreciated
