### ISSUE TITLE
Plato does not respond to touch on Glo

### ISSUE THREAD

**Issue by NoDuff** [baskerville/plato#215]
I recently installed Plato on my older Glo HD and when I launch it the Kobo stops responding to touch at all and can only be put to sleep or forcibly powered off. I have tried both 0.9.23 and 0.9.24 with the same results. For comparison the latest version of koreader works fine.

Additionally I have no issues with Plato my Aura H20 or Clara HD.

**Comment by baskerville** [comment]
I can't reproduce on my *Glo HD*. Is there anything unusual in *info.log*?

**Comment by NoDuff** [comment]
Here are the highlights of info.log

Can't load settings: can't read file Settings.toml: No such file or directory (os error 2).
Add new entry:  [followed by hash / title; for several books]
Plato is running on a Kobo Glo.
The framebuffer resolution is 758 by 1024.
Update fingerprint for [title/hash; for the same books]
Plato is running on a Kobo Glo.
The framebuffer resolution is 758 by 1024.
Went to sleep on January 10, 2022 at 16:38.
Woke up on January 10, 2022 at 17:01.
Plato is running on a Kobo Glo.
The framebuffer resolution is 758 by 1024.

**Comment by baskerville** [comment]
Please try the attached test binary that logs the relevant touch events.

Perform a tap, a swipe and post the resulting *info.log*.

[plato-glo-test-01.zip](https://github.com/baskerville/plato/files/7872734/plato-glo-test-01.zip)

**Comment by NoDuff** [comment]
[info.log](https://github.com/baskerville/plato/files/7873987/info.log)

Here is the log as requested.

**Comment by baskerville** [comment]
Thanks, it was quite useful.

Can you try the attached binary and confirm that the problem is fixed?

[plato-glo-test-02.zip](https://github.com/baskerville/plato/files/7875435/plato-glo-test-02.zip)

**Comment by NoDuff** [comment]
Yes, this new build works much better. It responds to touch as expected and I can read books and access the menus.

Thank you.
