### ISSUE TITLE
Touch screen not responding on Kobo Glo N613

### ISSUE THREAD

**Issue by nikovuksan** [baskerville/plato#216]
- Device: Kobo Glo N613

Issue:

Touchscreen not responding on Kobo Glo N613 from Plato 0.9.21 to Plato 0.9.24, with earlier versions like Plato 0.9.20 it works without problems. I think it may be due to "Fix the implementation of the touch protocol used by the Elipsa, Sage, and Libra 2 in version Plato 0.9.21"

**Comment by NoDuff** [comment]
Duplicate of #215 

I already brought this issue to the attention of the dev and it has been fixed and will be part of the next release.
