### ISSUE TITLE
[Feature Request] PowerCover battery level?

### ISSUE THREAD

**Issue by pedropachecog** [baskerville/plato#217]
Hi, I was wondering if the battery level of the Sage PowerCover could be displayed. As of now, it is necessary to go back to the standard software to see it.

**Comment by baskerville** [comment]
@NiLuJe Are there messages written to `/tmp/nickel-hardware-status` when the *PowerCover* is connected or disconnected?

**Comment by NiLuJe** [comment]
I haven't checked, but I wouldn't necessarily thing so. There's nothing I can do the kernel uevent feed, at the very least.

I keep forgetting to check event0, but I wouldn't hold my breath, the battery applet in nickel seems to poke at the full set of sysfs entries.

**Comment by NiLuJe** [comment]
Yup, nothing on event0 either.

So, nothing I can think of to detect the cover in a nice, event based approach. Have to poke at sysfs :/.

(I mean, it does have a tendency to trigger bogus usb_plug or usb_host uevents, but that doesn't count ;p).

**Comment by baskerville** [comment]
@NiLuJe Could you try the attached binary? If the *PowerCover* is connected, tapping the battery widget should yield a menu with two entries.

[plato-power_cover-01.zip](https://github.com/baskerville/plato/files/8119794/plato-power_cover-01.zip)

**Comment by NiLuJe** [comment]
I'll get back to you on Sunday ;).

**Comment by NiLuJe** [comment]
Whee, I'm late ;).

This fails to start on a fresh install:

```
Can't load settings: can't read file Settings.toml: No such file or directory (os error 2).
Error: can't build context

Caused by:
    0: can't create battery
    1: No such file or directory (os error 2)
```
