### ISSUE TITLE
Show book cover when changing to sleep mode

### ISSUE THREAD

**Issue by pachi** [baskerville/plato#218]
Besides being able to change the static image that appears when going into sleep mode, it would be very cool that Plato allows to automatically set this to the current book front cover image. I miss being able to see it when using the ebook, as I must confess that it makes me easier to remember the book and its name.

**Comment by occivink** [comment]
I've not tried it myself, but [`Settings-sample.toml`](https://github.com/baskerville/plato/blob/master/contrib/Settings-sample.toml#L60-L66) mention a special `cover:` value for intermissions, which I think does what you want.

**Comment by pachi** [comment]
Oh, that could be it! I couldn't find it in the documentation and it surprised me that anybody else found it useful.
I will try it and report here!

**Comment by pachi** [comment]
That indeed did it!

I think there's no option to change this in the UI so, to change that setting, just open the Settings file in the Plato directory (in my Kobo Reader that's KOReader/.adds/plato/Settings.toml) and change this section according to your preferences:

```
# Defines the images displayed when entering an intermission.
# Possible values: "logo:", "cover:", "/path/to/image/file".
# If a relative file path is given, it will be relative to
# the installation directory.
[intermissions]
suspend = "cover:"
power-off = "cover:"
share = "logo:"
```

In my case, I changed the default "logo:" preference for the power-off and suspend events to "cover:".

Thanks again @occivink !

**Comment by lucasmbrown** [comment]
For those new to `plato`, you can edit `Settings.toml` after finding it in (at least for Kobo): `<Your e-reader volume/.adds/plato/`.
