### ISSUE TITLE
Gyroscope rotation is inverted on Kobo Elipsa

### ISSUE THREAD

**Issue by CryptedSystem** [baskerville/plato#219]
On the kobo elipsa the interface is always upside down when the rotation is left on automatic. Firmware 4.31.

**Comment by baskerville** [comment]
Do you mean that the interface is upside down when you hold the device in landscape mode?

What version are you running (main menu, *About*)?

**Comment by CryptedSystem** [comment]
No matter the rotation the interface is upside down, it does detect a change in rotation and updates but it rotates the interface exactly opposite of the device's orientation. 

I'm running version 0.9.25

**Comment by baskerville** [comment]
Could you try the attached binary and see if it solves the problem?

[plato-elipsa-01.zip](https://github.com/baskerville/plato/files/7965867/plato-elipsa-01.zip)

**Comment by CryptedSystem** [comment]
It works like a charm, thank you very much
