### ISSUE TITLE
Kobo nia support

### ISSUE THREAD

**Issue by Szybet** [baskerville/plato#220]
I own a kobo nia and I tryied to install plato on it. It launches, it shows the books, it responds to USB to PC connection, it responds also to the shutdown button. It seems everything works but not the touch screen. I know that plato doesn't support this device, but i saw in the code some things related to Nia, like the screen resolution. I have some experience with linux, and with rust so i think that i could make it work. And here is my question, where to look, where to start, where is the code related to the touch screen?

**Comment by baskerville** [comment]
Please try the attached test binary that logs the relevant touch events.

Perform a tap, a swipe and post the resulting *info.log*.

[plato-nia-01.zip](https://github.com/baskerville/plato/files/8026040/plato-nia-01.zip)

**Comment by Szybet** [comment]
First i performed taps and after reboot some swipes
It doesn't detect any books becouse after i put the binary and tryied to reboot, the kobo nia resetted itself. Its propably my fault, becouse i holded the button too long.

[info.log](https://github.com/baskerville/plato/files/8027696/info.log)

**Comment by baskerville** [comment]
Could you try the attached binary (this is a modified version of *Plato* that sets *Rotation Values* as the initial view), follow the instructions and post the resulting *info.log*?

[plato-nia-02.zip](https://github.com/baskerville/plato/files/8027936/plato-nia-02.zip)

**Comment by Szybet** [comment]
here it is

[info.log](https://github.com/baskerville/plato/files/8028089/info.log)

**Comment by baskerville** [comment]
Please try the attached binary and see if the touch screen now works as expected within all the available portrait and landscape orientations.

[plato-nia-03.zip](https://github.com/baskerville/plato/files/8031038/plato-nia-03.zip)

**Comment by baskerville** [comment]
@NiLuJe It would seem that the *Nia* uses the *Phoenix* touch protocol.

**Comment by NiLuJe** [comment]
Huh. Good to know, thanks ;). Nia users are so few and far between that
it's hard to tell..

**Comment by Szybet** [comment]
everything works, but once the custom zoom option in a pdf crashed plato, also i don't know how to regulate the custom zoom percantage, it sometimes changes but i don't know why the [link](https://github.com/baskerville/plato/blob/master/doc/MANUAL.md) doesn't help
