### ISSUE TITLE
Notes aren’t persisted between restarts on reMarkable

### ISSUE THREAD

**Issue by leeuwerck** [baskerville/plato#226]
Hi,

I’m using Plato 0.9.13 on my reMarkable 1 tablet. I usually synchronize files with scp with a directory at `/home/root/plato-media`. Sometimes a book I’d been reading disappears from the top of my list ordered by last opened, and the notes I’ve taken in the book disappear.

Any idea how to fix this? Where are notes supposed to be saved?

Cheers and thanks again for this awesome piece of software.

**Comment by baskerville** [comment]
The reading states are saved in a directory named `.reading-states` in each library's *path*.
