### ISSUE TITLE
How to list Annotations and Highlights ?

### ISSUE THREAD

**Issue by leeuwerck** [baskerville/plato#227]
Hi,

Is there a feature to list all annotations and highlights made to an .epub file?

Have a great day

**Comment by baskerville** [comment]
With the EPUB opened, bring up the book menu and select *Annotations*.

**Comment by thisisphan** [comment]
Hey, what did you mean by the book menu?
I'm not seeing the annotations option on that screen.
https://cdn.discordapp.com/attachments/859275983701278724/1029284988157448222/IMG_0855.jpg

**Comment by baskerville** [comment]
Tap the title in the top bar.

**Comment by yasirbilgic** [comment]
Is there a way to annotate a pdf?
