### ISSUE TITLE
[feature]: internationalization (i18n) support

### ISSUE THREAD

**Issue by pazos** [baskerville/plato#23]
a big **Thank you** to @baskerville for plato and other great contributions to free software. Thanks again.

I would like to know if you are going to support translations anytime soon. Not a big deal to have the ui in english but it would be great.

**Comment by shytikov** [comment]
I think the biggest problem is search here. You can search in English only. Basically if you have your book in any other language you stuck.

**Comment by baskerville** [comment]
> I think the biggest problem is search here. You can search in English only. Basically if you have your book in any other language you stuck.

The notion of keyboard layout exists, but hasn't been externalized yet.

Another related problem is that RTL scripts aren't supported.
