### ISSUE TITLE
Element is not displayed if class attribute value is not quoted

### ISSUE THREAD

**Issue by thataboy** [baskerville/plato#233]
I encountered a book where some paragraphs were not showing up in Plato. I finally figured out the problem

```
<html>
<body>
<p class=foo>hello, world</p>
</body>
</html>
```

This file will show up blank in Plato because foo is not quoted. The HTML specs say

>Attributes are placed inside the start tag, and consist of a name and a value, separated by an = character. The attribute value can remain unquoted if it doesn’t contain spaces or any of " ' ` = < or >.

**Comment by baskerville** [comment]
What do you get when you run *EPUBCheck* on the aforementioned book?

**Comment by thataboy** [comment]
You're right it doesn't pass epubcheck because of the unquoted attribute value. I guess it's the book's fault, though perhaps the epub reader should be more lenient on this point?
