### ISSUE TITLE
Gyroscope and buttons doesn't seem to work on Kobo Libra 2

### ISSUE THREAD

**Issue by denishem** [baskerville/plato#247]
Hi,

I installed Plato using the OCP. It launches fine, but I am unable to use the buttons on the Kobo Libra 2 and the gyroscope doesn't work. Is this something expected ? Do I have to enable them somehow ? I am using the latest FW and latest OCP.

**Comment by baskerville** [comment]
I think I'll have to integrate some of the changes from https://github.com/NiLuJe/koreader/commit/480598a302b34eb9a87fdeb5fdf3fe5999a0e6d1.

**Comment by baskerville** [comment]
Could you try the attached binary?

[plato-libra2_rev2-inputs.zip](https://github.com/baskerville/plato/files/9065421/plato-libra2_rev2-inputs.zip)

**Comment by denishem** [comment]
With the attached binary I'm unable to launch Plato. It brings me back to Nickel without any hint on what happened. What is the procedure to get a log?

**Comment by baskerville** [comment]
Please post the relevant error messages you'll find at the end of *info.log* (saved alongside the *plato* binary).

**Comment by baskerville** [comment]
My bad: I know what's making it crash: I've upgraded MuPDF after 0.9.28.
