### ISSUE TITLE
Settings.toml auto-revert

### ISSUE THREAD

**Issue by neeasade** [baskerville/plato#250]
Hi, 

My `Settings.toml` doesn't appear to retain any changes (version: 0.9.30). I have tried connecting from plato ("shared mode") and also quitting plato and connecting with the vanilla setup. 

To edit Settings.toml, I'm mounting the kobo at `~/mount` and then editing `~/mount/.adds/plato/Settings.toml` -- but when I `umount` and go back to the reader, none of the edits stick around/apply. If I re-mount I see an old version of `Settings.toml` come up.

note: first time plato user

**Comment by baskerville** [comment]
It can happen if `/mnt/onboard` is lazily unmounted. *Plato*'s script, `scripts/usb-enable.sh`, first tries to unmount cleanly and then fallbacks to the lazy method. The vanilla script always lazily unmounts. You could prevent this by having *Plato* partially installed in `/usr/local` (cf. `standalone.sh`).

You might also want to check for any error messages related to `Settings.toml` in `info.log` (saved alongside *Plato*'s binary): if there's a typo in `Settings.toml`, the default settings are used (and written to `Settings.toml` when *Plato* quits).

**Comment by neeasade** [comment]
> You might also want to check for any error messages related to Settings.toml in info.log (saved alongside Plato's binary): if there's a typo in Settings.toml, the default settings are used (and written to Settings.toml when Plato quits).

ah yepp! thanks

I made a bad assumption:

> Can't load settings: can't parse TOML content from Settings.toml: unknown variant `none`, expected `toggle-bars` or `next-page` for key `reader.south-strip` at line 130 column 1.
