### ISSUE TITLE
How to set zoom mode to PageWidth?

### ISSUE THREAD

**Issue by paulrouget** [baskerville/plato#251]
I'm reading some graphics novels, and I'd like the page to have an auto-crop and fit to page width. How would I achieve that?

**Comment by paulrouget** [comment]
>  tap the title of the document in the top bar

Oh, that was well hidden :) Thank you!

**Comment by baskerville** [comment]
You can also set the zoom mode to *fit-to-width* by performing an [horizontal spread gesture](https://github.com/baskerville/plato/blob/master/doc/MANUAL.md#viewer).
