### ISSUE TITLE
Would it be ok to use Rust workspaces?

### ISSUE THREAD

**Issue by paulrouget** [baskerville/plato#256]
I was looking for a way to remove all the warnings, but the use of the multiple `[[bin]]` (plato/importer/emulator/fetcher) make it almost impossible to avoid dead code.

I think it make more sense to use workspaces to have 4 crates for binaries, and one crate as a core lib.

If that's something you would be ok with, I will give it a shot.

**Comment by baskerville** [comment]
Yes, it would be great if you can find a way to eliminate the warnings.

**Comment by paulrouget** [comment]
> Yes, it would be great if you can find a way to eliminate the warnings.

Ok. I'll look into it.
