### ISSUE TITLE
MacOS toolchain

### ISSUE THREAD

**Issue by paulrouget** [baskerville/plato#258]
So far I've been using docker to build plato. But I'd rather build it locally on my Mac.

The documentation links to the toolchains: https://github.com/kobolabs/Kobo-Reader/tree/master/toolchain - but this repository has issues https://github.com/kobolabs/Kobo-Reader/issues/102 making it impossible to download the toolchains.

Any idea where to find a compatible toolchain for osx?

**Comment by baskerville** [comment]
Here's a [download link](https://www.dropbox.com/s/u4wtdik36f6mbqq/gcc-linaro-4.9.4-2017.01-20170615_darwin.tar.bz2?dl=1) to the proper toolchain (The MD5 sum is 17f56603c9ceb8d6fc0bab87645fe430).

**Comment by paulrouget** [comment]
Thank you!
