### ISSUE TITLE
Abbreviating long tags

### ISSUE THREAD

**Issue by themanifold** [baskerville/plato#26]
Small UX suggestion; I have some really long tags in my book collection. As it stands, it takes the whole width of the screen so I can't easily see another tag to filter by. Could we abbreviate tags to some smaller default (7 characters or something customizable)? Thanks.

**Comment by baskerville** [comment]
I've made a first step in this direction, by reducing the maximum length of a category in fe5ec6e. Please note that you can grow the summary bar by swiping from the inside to the outside of the bar. You can also set the initial vertical size through the `home.summary-size` setting.

Can you provide an example of a very long category name?

**Comment by themanifold** [comment]
Thanks. I bought a book from Pact that had a ridiculously long "Subject" field:
```
COM014000 - COMPUTERS / Computer Science|COM017000 - COMPUTERS / Cybernetics|COM083000 - COMPUTERS / Security / Cryptography
```

It seems to be a common theme for ebook publishers to separate subject fields by a slash, maybe plato could split them into separate tags?

While we're at it, which metadata fields does plato look at for tags?

**Comment by baskerville** [comment]
Thanks, this is quite useful.

Please note that *Plato* deals with hierarchical categories, not tags.

The categories are imported from:
- The directory structure relative to `LIBRARY_PATH`: a book in `LIBRARY_PATH/a/b/c` will have a default category of `a.b.c`.
- The `dc:subject` tags for ePUBs (in addition to the directory structure).

In the example you've given, the subject is a list of [BISAC Subject Headings](https://bisg.org/page/Computers).

The separator is `|`. If we discard the category codes, it would translate into the following categories:
```
COMPUTERS.Computer Science
COMPUTERS.Cybernetics
COMPUTERS.Security.Cryptography
```

It would indeed be interesting to try to detect if the `dc:subject` tag is using BISAC categories.

**Comment by baskerville** [comment]
Just out of curiosity, does the aforementioned ePUB has a `dc:contributor` tag with `opf:role="bkp"`? And if it does, what's the tag's content?
