### ISSUE TITLE
Clara 2E Support

### ISSUE THREAD

**Issue by TheWranger** [baskerville/plato#267]
Support for the Clara 2E would great. Currently, the program boots but doesn't respond to the touch screen at all.

**Comment by baskerville** [comment]
Could you try the attached binary, select *Applications → Rotation Values* in the main menu, follow the instructions and post the resulting *info.log*?

[plato-clara_2e-test01.zip](https://github.com/baskerville/plato/files/9847013/plato-clara_2e-test01.zip)

**Comment by vivithecanine** [comment]
It doesn't seem possible to select anything on the screen at all, or rather, you can click things but they never do anything (ver 0.9.33)

![IMG_20221107_163106_116](https://user-images.githubusercontent.com/90877136/200429992-539395d2-4bd8-4fb7-8c4c-1b05648a4c5a.jpg)

**Comment by baskerville** [comment]
Could you try the attached binary?

[plato-clara_2e-test02.zip](https://github.com/baskerville/plato/files/9959219/plato-clara_2e-test02.zip)

**Comment by baskerville** [comment]
The rotations values seems fine already.

Does the interface rotate correctly when you rotate the device?

**Comment by vivithecanine** [comment]
I have Gyroscope set to Auto (the default) and it does not rotate

**Comment by TheWranger** [comment]
Sorry, went overseas the day I made this issue and haven't had till now. Frontlight (as well as warmth control) and WiFi seem to be working fine with this binary. Thanks!
> [plato-clara_2e-test02.zip](https://github.com/baskerville/plato/files/9959219/plato-clara_2e-test02.zip)
