### ISSUE TITLE
Crash on specific epub

### ISSUE THREAD

**Issue by themanifold** [baskerville/plato#27]
This ebook (http://lise-henry.github.io/books/trpl2.epub) always crashes my Plato out to KSM. The source to generate the epub is here (https://github.com/lise-henry/books/blob/master/README.md). I'm using a Kobo Touch.

**Comment by baskerville** [comment]
Unfortunately, this will happen with all the ePUBs generated with crates that depend on a version of [epub-builder](https://github.com/lise-henry/epub-builder) that predates my [pull request](https://github.com/lise-henry/epub-builder/pull/3).

**Comment by themanifold** [comment]
Am I right in saying that it will throw an error rather than crashing out now?
