### ISSUE TITLE
Typo on "About" Screen

### ISSUE THREAD

**Issue by tgfrerer** [baskerville/plato#276]
I believe this should say `Firmware`, not `Firmare` :)

https://github.com/baskerville/plato/blob/c6839129f35485e6fb5e269711fc8236cc2fe327/crates/core/src/document/mod.rs#L485

And by the way: thank you for this wonderful piece of Software, it makes reading books on my Kobo an absolute delight! <3

**Comment by baskerville** [comment]
You're welcome.
