### ISSUE TITLE
Questions around the manual and other topics.

### ISSUE THREAD

**Issue by rvlander** [baskerville/plato#282]
First I would like to emphasize on P the fact that Plato is way faster and smart compared to the native Kobo software. I am grateful that you worked on this project.

I am trying to find the best features to navigate back and forth in a pdf with lots of references (but no links).

Using *a bookmark stack* and  *go to page feature*  seem the way to go and I have seen in the manual how to bookmark a page. But how to navigate them ? The manual references a method in a particular zoom mode (custom), but we don't know how to enter this mode. Can I navigate bookmarks easily in normal mode ? Can I get a list of bookmarks ?

Gestures does not seem to be supported on my old Kobo touch, what are the alternatives to access the corresponding functionalities ?

It's project like yours that enable to improve devices lifetime, have you looked if you could get some help from EU subventions ?

**Comment by thataboy** [comment]
Tap in center to bring up the UI, then tap on the book's title to show the drop down menu and tap Bookmarks.

You can go to prev bookmark by drawing a ┌  next bookmark by drawing a ┐

**Comment by rvlander** [comment]
Thanks for your explanations. I wanted to update the MANUAL with these but they seem to already present (albeit they did not made sense the first time I read them).
Sorry for the inconvenience.

Closing.
