### ISSUE TITLE
Enhancement: add DOI to metadata/importer?

### ISSUE THREAD

**Issue by taosxx** [baskerville/plato#3]
It seems that metadata.rs includes placeholders for ISSN and ISMN identifiers. Would it make sense to add DOI ([http://www.doi.org/](url)) one day to retrieve metadata for articles from e.g. scientific journals? Not sure if something like Crossref's REST API [https://github.com/CrossRef/rest-api-doc](url) and rcrossref [https://github.com/ropensci/rcrossref](url) could be used to request the metadata.

**Comment by baskerville** [comment]
I could add a retriever based on the DOI.

But the problem is the extractor: the papers don't mention their DOI.

**Comment by taosxx** [comment]
According to the documentation it seems that you can extract the ISBN as long as:
1.) the document does have an OCR text layer that is not scrambled,
2.) the ISBN is given and listed on the first ten pages.

Thus, I assumed that you don't have to extract the information from e.g. an .opf file in an epub or the actual metadata of a pdf file but you're searching the first 10 pages (of a pdf?) for the first mention of "isbn" and an associated number that looks like a valid ISBN number. If that's the case, a lot of (but of course not all) downloaded pdfs from journals can be searched and include a DOI either on the first, second or last page.

BTW, is the use of "retreive" as function name instead of retrieve intentional?

**Comment by baskerville** [comment]
> Thus, I assumed that you don't have to extract the information from e.g. an
> .opf file in an epub or the actual metadata of a pdf file but you're
> searching the first 10 pages (of a pdf?) for the first mention of "isbn" and
> an associated number that looks like a valid ISBN number.

That's correct. There's also `-M` to extract the metadata from the document's
metadata: this is mostly useful for ePUBs.

> If that's the case, a lot of (but of course not all) downloaded pdfs from
> journals can be searched and include a DOI either on the first, second or
> last page.

I've looked at twenty articles from my library and I didn't find any DOI.

> BTW, is the use of "retreive" as function name instead of retrieve intentional?

That's a typo, thanks for catching it.
