### ISSUE TITLE
Freezing On Boot After Adding Dictionary?

### ISSUE THREAD

**Issue by seniorm0ment** [baskerville/plato#303]
After adding the stardict dictionary from here
https://raw.githubusercontent.com/BoboTiG/ebook-reader-dict/master/docs/en/README.md

By unzipping (not the dictionary but just the archive download so there's the multiple files), and placing all the files into plato/dictionaries

Upon launching plato, kfmon says launching and the device just freezes. Wait a minute and nothing. 

Force reboot the kobo, attach to pc and delete the files from the dictionaries folder and eject. Plato works no issues.

Kobo Libra 2

**Comment by baskerville** [comment]
_StarDict_ dictionaries are converted to _dictd_ via `convert-dictionary.sh`. This process might take a very long time on an e-reader. If you have access to a computer, I would recommend [converting](https://github.com/baskerville/sdunpack#convert-stardict-to-dictd) the dictionaries yourself.

**Comment by seniorm0ment** [comment]
Ah ok, so it is simply converting them upon load. I will report back when I get it working

**Comment by seniorm0ment** [comment]
This seemed to work thanks

**Comment by symgryph** [comment]
How did you exactly add the dictionary? I put the 'dict' version in the plato/dictionaries (uncompressed) and nothing happened.

**Comment by baskerville** [comment]
> I put the 'dict' version in the plato/dictionaries (uncompressed) and nothing happened.

If you mean the *DictFile* version, then the outcome is expected. The only supported formats are *dictd* and *StarDict*.
