### ISSUE TITLE
[Feature Request] Option To Enable NickelMenu Within Plato

### ISSUE THREAD

**Issue by seniorm0ment** [baskerville/plato#309]
From what I can tell, unless it is a config setting I missed, NickelMenu does not seem to work within Plato. The bar at the bottom of my device completely disappears. So NickelMenu does not appear.

**Comment by NiLuJe** [comment]
Because you're no longer running Nickel *at all*

What you're asking for is technically unfeasible (because it makes no sense in the first place).

**Comment by seniorm0ment** [comment]
So nickel does not run whilst plato is open? Oh
