### ISSUE TITLE
[Feature Request] Option To Hide Author Search Bar At Library

### ISSUE THREAD

**Issue by seniorm0ment** [baskerville/plato#310]
There might be a way to do this in the config file of Plato, or the css but I did not see it when looking. 
I would really appreciate being able to hide the entire bar on the library screen, at the top, where it shows all author names. You click an author, and it filters books by that author. I personally do not use it, and it just clutters the screen and shows less books.

**Comment by baskerville** [comment]
What you're referring to is the [Navigation Bar](https://github.com/baskerville/plato/blob/master/doc/MANUAL.md#navigation-bar). You can hide it by following the instructions in the manual or by setting *navigation-bar* to *false* in the *home* section of *Settings.toml*.
