### ISSUE TITLE
[Issue] 30% battery drain in 24 hours in sleep mode

### ISSUE THREAD

**Issue by rafcon-dev** [baskerville/plato#313]
Hello. I have a kobo libra 2. I love the interface speed and minimalism of Plato. However, I've run into an issue regarding battery usage. With the default ui, on sleep mode the battery drains around 1%-2% per day, which I believe is fine. However, with Plato in sleep mode I get a small drain for one day or two, but then in 24 hours it gets drained like 30%. How can I better pinpoint what might be causing this?

**Comment by NiLuJe** [comment]
Are you using a sleep cover?

**Comment by rafcon-dev** [comment]
I have stopped using it as I had read it might cause these issues, so no

A sábado, 5/08/2023, 17:35, NiLuJe ***@***.***> escreveu:

**Comment by baskerville** [comment]
Please follow the instructions given in [this comment](https://github.com/baskerville/plato/issues/307#issuecomment-1666799059).

**Comment by rafcon-dev** [comment]
I have read that thread and I've installed the latest Plato binary you mentioned at the end. I'll test it for a few days and see how it goes. Thanks!

**Comment by baskerville** [comment]
> I have read that thread and I've installed the latest Plato binary you mentioned at the end.

Since you don't have a *SleepCover*, you'd better just follow the instructions given the aforementioned comment.

**Comment by rafcon-dev** [comment]
Ok, I've done that then, let's see. Cheers

**Comment by rafcon-dev** [comment]
Here is a log file. Massive battery drain to 0 in the last couple days, from about 50% or so
Thank you for your time, looking forward to an update on this
[archive.log](https://github.com/baskerville/plato/files/12591690/archive.log)

**Comment by baskerville** [comment]
You're not using a sleep cover, but you do have lots of sleep cover events in your log, hence you must have magnets near your device when it rests.

**Comment by rafcon-dev** [comment]
That's quite weird. I suppose then that it'd get solved by the changes to the handling of VAL_REPEAT in the latest version?

**Comment by baskerville** [comment]
> I suppose then that it'd get solved by the changes to the handling of VAL_REPEAT in the latest version?

Yes, it should.

**Comment by rafcon-dev** [comment]
Hey again. Unfortunately it doesn't seem to have solved the issue. Just a couple hours ago I left it with no cover, and went from 35%->8%. Can you send me a logging executable again so we can pinpoint this?

Thank you for your time.

**Comment by rafcon-dev** [comment]
Here is the log file. It should contain a recent battery drop of like 15% in one day or two I believe.
[archive.zip](https://github.com/baskerville/plato/files/13895020/archive.zip)

**Comment by baskerville** [comment]
It seems you're using the previous logging binary (the *went to sleep*/*woke up* timestamps are more precise as of 0.9.40).

What's the value of `auto-power-off` in `Settings.toml`?

**Comment by rafcon-dev** [comment]
That's weird, I do believe I have replaced the binary with the latest you posted. I do have 0.9.40. I'll replace it again for good measure

That value is: 
auto-power-off = 3.0

Cheers!

**Comment by baskerville** [comment]
The comment about the binary was probably wrong. I was puzzled by the log and didn't notice something much more problematic : it stops 29 hours after September 24, 2023!

**Comment by rafcon-dev** [comment]
ahem, that's strange, sorry about that, I deleted the file and a new one was created, here is a new one. Had a battery drain to 0 a few days ago, and now 30% in a couple days.
[archive.log](https://github.com/baskerville/plato/files/13999205/archive.log)

Again, thank you!

**Comment by NiLuJe** [comment]
If it's plugged in at the time, possibly charge thresholds being crossed?

The usual culprit is the hall sensor, though, but you should be seeing the matching input events if it's logging those :s.

The gyro is a wakeup source, too, but only from standby, not suspend, so that *one* ought to be out...

**Comment by NiLuJe** [comment]
That leaves the RTC, which could be dodgy (the broken time would certainly leads credence to that theory...).

**Comment by rafcon-dev** [comment]
Here's a new log, with the correct time. I checked on it almost every day for a couple weeks, and it lost around 1-2% per day, until around 50%. 
Checked on it today and it was dead, in around 2 days. From the logs apparently it woke up by itself after I checked up on it and never went to sleep again?
[info.log](https://github.com/baskerville/plato/files/14234592/info.log)

**Comment by baskerville** [comment]
Thanks, I think I understand the bug now.

**Comment by rafcon-dev** [comment]
That's awesome, at last the nasty critter shall be squished! Best of luck, and thank you!

**Comment by baskerville** [comment]
Please try the attached binary and see if it's fixed.

[plato-0.9.40-fix_313-01.zip](https://github.com/baskerville/plato/files/14269793/plato-0.9.40-fix_313-01.zip)

**Comment by rafcon-dev** [comment]
Thank you, will report back in a few days!

**Comment by samriggio** [comment]
> Please try the attached binary and see if it's fixed.
> 
> [plato-0.9.40-fix_313-01.zip](https://github.com/baskerville/plato/files/14269793/plato-0.9.40-fix_313-01.zip)

I was having a similar issue with battery drain, but there's been no issues the past week using the "fixed" binary. 👍

**Comment by rafcon-dev** [comment]
Can confirm, seems to be solved, got around 2% per day with some light usage!
Thank you very much for your work, bought you a coffee.
