### ISSUE TITLE
Add the Elipsa 2E to the list of supported devices.

### ISSUE THREAD

**Issue by jlb6907** [baskerville/plato#315]
Please, add the Kobo Elipsa 2E to the list of supported devices. (I have a crash with plato 0.9.38).

**Comment by baskerville** [comment]
Could you try the attached package? Please test rotating your device to see if the display matches the orientation.

[plato-0.9.38-elipsa_2e.zip](https://github.com/baskerville/plato/files/12579548/plato-0.9.38-elipsa_2e.zip)

**Comment by jlb6907** [comment]
Thanks a lot, I will try it tomorrow night.

**Comment by baskerville** [comment]
You'll have to extract the archive in *.adds/plato* and overwrite if asked. If you encounter a crash, please post the content of *info.log*.

**Comment by benkaiser** [comment]
Just tested that package on my Elipsa 2E. Can I ask what modifications were made? I'm wanting to build [the chess fork](https://github.com/baskerville/plato/pull/281) from scratch.

**Comment by jlb6907** [comment]
Just test on my Ellipsa 2E, it's perfect with "Portrait" mode, but it's backwards in "Landscape" mode. 
![Landscape](https://github.com/baskerville/plato/assets/4329562/03ffb41c-7816-4992-b971-ee68bc4e780c)

**Comment by baskerville** [comment]
It should be fixed in the attached binary.

[plato-0.9.38-elipsa_2e-01.zip](https://github.com/baskerville/plato/files/12590052/plato-0.9.38-elipsa_2e-01.zip)
