### ISSUE TITLE
some  issues about non-latin languages

### ISSUE THREAD

**Issue by Artlantic** [baskerville/plato#32]
Your plato-reader is fluency, but I met some issues with the recent version:
I'm a Chinese reader, Chinese words are not split by blank char, so one paragraph only displays the top several words, and the following is "..." in one line (eg: XXXXXXXX...), but the English books seem to be fine. So I supposed that the code may splits the paragraph to lines by blank. Is it possible to fix that? 
(my font is Droid sans fallback, my device is H2O. The font in screenshot picture is another one. Japanese or Korean might have similar problems) 
Thanks.

I'm glad to give assistance on test or translation if in need. 
![screenshot-20120605_022830](https://user-images.githubusercontent.com/28704378/50589013-ab7ab980-0ebf-11e9-8c2a-cb46825f6c57.png)

**Comment by baskerville** [comment]
Indeed, the built-in ePUB engine relies on word spaces. Could you provide a sample paragraph? I'd like to test if [UAX #14](http://www.unicode.org/reports/tr14/) can find the proper break points.

**Comment by Artlantic** [comment]
Thanks for reply.
// utf-8 code
UTF-8编码是用以解决国际上字符的一种多字节编码，它对英文使用8位（即一个字节），中文使用24位（三个字节）来编码。
I think this paragraph is long enough, I also provide a epub file.
[sample.zip](https://github.com/baskerville/plato/files/2720812/sample.zip)

**Comment by Artlantic** [comment]
From [http://www.unicode.org/reports/tr14/tr14-41.html](url)
Three principal styles of context analysis determine line break opportunities.
1. Western: spaces and hyphens are used to determine breaks
2. East Asian: lines can break anywhere, unless prohibited (Chinese is belong to this.)
3. South East Asian: line breaks require morphological analysis

**Comment by hpfr** [comment]
@baskerville I'm going to comment here since it seems to be related. Plato breaks lines on certain punctuation it shouldn't like quotation marks for me:

possibly “
Friends,”

instead of:

possibly
“Friends,”

Can you reproduce this? Maybe something with the line break iterator from `xi-unicode` is wrong?

Thanks for Plato!

**Comment by baskerville** [comment]
- You should create a new issue.
- It will be hard to reproduce without the actual HTML code.
