### ISSUE TITLE
Bad Rendering of MOBI Books

### ISSUE THREAD

**Issue by baskerville** [baskerville/plato#321]
I would seem that the output we get when rendering MOBI books within _Plato_ differs from the output we get with `mutool draw…`. The most noticeable problem is that the font sizes are reversed in the _Plato_ output.

**Comment by baskerville** [comment]
I've made some progress : I'm getting a correct output when I comment out [this line](https://github.com/baskerville/plato/blob/a0d615a64dc5e4f3ac045ab04b12dd598e0468c4/crates/core/src/view/reader/mod.rs#L252).

**Comment by NiLuJe** [comment]
MuPDF may be hardcoding something like 72 or 96 dpi, maybe?

**Comment by baskerville** [comment]
_mutool_ uses the default layout values (`FZ_DEFAULT_LAYOUT_{W,H,EM}`), so the `fz_layout_document` call (implemented as `fz_layout_html` for MOBI documents) returns without doing anything. But _mutool_ has layout parameters, so I might be able to reproduce the bug using only *mutool*.

**Comment by baskerville** [comment]
[Upstream bug report](https://bugs.ghostscript.com/show_bug.cgi?id=707183).

**Comment by baskerville** [comment]
My guess is that the problem comes from the fact that _MuPDF_ interprets the `size` attribute of the archaic `font` tag [in points](https://github.com/ArtifexSoftware/mupdf/blob/e32a0e27163cccc98eb4b509ea1493cdac8b4930/source/html/html-parse.c#L1624-L1632), instead of using ems.

**Comment by baskerville** [comment]
[Fixed upstream](https://git.ghostscript.com/?p=mupdf.git;h=4ae522a299df7e18f155ae319c7756298d69c490).
