### ISSUE TITLE
Need advice on debugging startup issues

### ISSUE THREAD

**Issue by kartikynwa** [baskerville/plato#326]
I was playing around with Settings.toml and the fonts folder and I did something that prevents Plato from starting up. When I select Plato from Nickel, I just get taken back to Nickel again. I tried reverting back the changes I made but could not pinpoint what the issue which is on me.

I have been reading GUIDE and MANUAL but I am not sure what I can do to debug. Could this be getting logged somewhere? 

If desired, I would also like to help incorporate instructions for debugging in the documentation. Sorry for polluting the issue stream but I didn't know where else to ask this.

**Comment by baskerville** [comment]
You'll find the error messages in `info.log` (in the installation directory).

**Comment by kartikynwa** [comment]
Thanks a lot.
