### ISSUE TITLE
autoshutdown in hours?

### ISSUE THREAD

**Issue by formula-spectre** [baskerville/plato#328]
the documentation says:
```
# The delay, in days, after which a suspended device
# will power off. *Zero* means *never*.
auto-power-off = 3.0
```
I get the first digit, it's days, but the second? I tried to set it to `0.2` for two hours, but it does not seem to be the right value? since after two hours it did not shut down. or maybe it did, and the screen did not change/i did not notice. I just had the book cover with white bars left and right.

**Comment by baskerville** [comment]
*0.2* days is *24/5* hours, so four hours and forty-eight minutes. Two hours is *2/24* days, about *0.0833* days.

**Comment by formula-spectre** [comment]
uhh I might sound stupid but can you explain the math behind?

**Comment by baskerville** [comment]
`auto-power-off` is just a decimal number.
