### ISSUE TITLE
Where does plato search for files?

### ISSUE THREAD

**Issue by Evidlo** [baskerville/plato#33]
I'm running plato on a non-Kobo device (reMarkable).  I've glanced through the source but I can't seem to figure out in what paths plato searches for documents.  Any tips?

**Comment by Evidlo** [comment]
Somehow I missed this when I glanced at GUIDE.md.

**Comment by Evidlo** [comment]
There seems to be a discrepancy somewhere.  `GUIDE.md` says to create a Settings.toml with `library-path` to set the search path, but this had no effect for me.  It wasn't until I modified `libraryPath` in the autogenerated `settings.json` that the search path changed.

**Comment by baskerville** [comment]
The format of the configuration file changed in 2f9519e.
