### ISSUE TITLE
device does auto power off after set amount of time

### ISSUE THREAD

**Issue by formula-spectre** [baskerville/plato#330]
might be related to https://github.com/koreader/koreader/issues/10996
this is my setting; 
[Settings.toml.txt](https://github.com/baskerville/plato/files/12893661/Settings.toml.txt)
i have the line
```
auto-power-off = 0.08330000191926956
```  
the suspension after 15 minutes works fine, it's the autopoweroff that does not work

**Comment by baskerville** [comment]
Are there any errors in _info.log_?

**Comment by formula-spectre** [comment]
I grepped for errors but I did not find any; here is the log, with the entry sed /d out for.. reasons  
https://termbin.com/c3nc

**Comment by baskerville** [comment]
The only surprising element from your log is the file fingerprint that keeps changing. What really changes is the relative modification time component (the first four bytes). It first jumps two hours backward, goes back to its previous state and then jumps one hour forward.

**Comment by formula-spectre** [comment]
might be related to https://github.com/koreader/koreader/issues/10996

**Comment by baskerville** [comment]
Could you:
- Quit *Plato*;
- Replace your *plato* binary with the one attached;
- Set `auto-power-off` to `0.02` in *Settings.toml*;
- Launch *Plato*, put your device to sleep and wait for 30 minutes;
- Wake your device and retrieve, in *info.log*, the passage that starts with *RTC Wake Alarm*?

[plato-0.9.39-touch_c-rtc01.zip](https://github.com/baskerville/plato/files/13006717/plato-0.9.39-touch_c-rtc01.zip)

**Comment by formula-spectre** [comment]
```
RTC Wake Alarm: RtcWkalrm {
    enabled: 1,
    pending: 0,
    time: RtcTime {
        tm_sec: 1,
        tm_min: 0,
        tm_hour: 0,
        tm_mday: 1,
        tm_mon: 0,
        tm_year: 70,
        tm_wday: 4,
        tm_yday: 1,
        tm_isdst: 0,
    },
```
there's also this:
```
Plato is running on a Kobo Touch C.
The framebuffer resolution is 600 by 800.
Went to sleep on October 19, 2023 at 09:30:43.
Woke up on October 19, 2023 at 09:59:30.
```

the rest is updated fingerprint/add new entry, but if you want the full log I can attach it!

**Comment by baskerville** [comment]
Thanks, could you:
- Quit *Plato*;
- Replace your *plato* binary with the one attached;
- Launch *Plato*, put your device to sleep and wait for two minutes;
- Wake your device up and retrieve, in *info.log*, the passage that starts with *RTC Wake Alarm*?

[plato-0.9.39-touch_c-rtc02.zip](https://github.com/baskerville/plato/files/13040149/plato-0.9.39-touch_c-rtc02.zip)

**Comment by formula-spectre** [comment]
```
RTC Wake Alarm: RtcWkalrm {
    enabled: 1,
    pending: 0,
    time: RtcTime {
        tm_sec: 1,
        tm_min: 0,
        tm_hour: 0,
        tm_mday: 1,
        tm_mon: 0,
        tm_year: 70,
        tm_wday: 4,
        tm_yday: 1,
        tm_isdst: 0,
    },
}
```
note: when I wake up the device instead it powers off completely; is this the new binary's doing?

**Comment by baskerville** [comment]
> When I wake up the device instead it powers off completely; is this the new binary's doing?

Yes : it's caused by a wrong assumption regarding the alarm.

**Comment by formula-spectre** [comment]
uh okay, so is the problem the RTC? is there any way it can be fixed?

**Comment by NiLuJe** [comment]
FWIW, I'm mildly curious what the read looks like *just* after the set, and not just after it *fired* (in case it just happens to reset to Epoch only *after* firing), but given that I'm pretty sure we've seen sane reads no matter what on the same device, it's mostly a theoretical at this point ;p. My best guess is it's a voltage related quirk, but the voltage read ioctl is *even more* unreliable.

**Comment by formula-spectre** [comment]
@NiLuJe wym

**Comment by NiLuJe** [comment]
Nah, that was some more contextual musings ;).

**Comment by formula-spectre** [comment]
oh okay :)

**Comment by baskerville** [comment]
> I'm mildly curious what the read looks like _just_ after the set

It looks like [this](https://github.com/baskerville/plato/issues/330#issuecomment-1770385318).

> (in case it just happens to reset to Epoch only _after_ firing)

That's what I was hoping for.

**Comment by NiLuJe** [comment]
Yeah, that would track with what I vaguely remembered *after* posting that from the [original report](https://github.com/koreader/koreader/issues/7994) we got of this ;).

**Comment by formula-spectre** [comment]
yep, this last one works, my kobo turned off after 30 minutes!

**Comment by formula-spectre** [comment]
so the next update is gonna work fine or am I gonna require a "special" binary?

**Comment by baskerville** [comment]
> So the next update is gonna work fine?

Yes.
