### ISSUE TITLE
ePub that makes everything super slow

### ISSUE THREAD

**Issue by bitboxer** [baskerville/plato#331]
Plato works flawlessly for most of my ePubs, except for one. I have no clue why, but when I open a specific one, the UI grinds to an halt, every page turn is super slow.

I would love to help and debug this, but I have no clue how to start. Any hints would be helpful <3

**Comment by baskerville** [comment]
Maybe you could start by running [epubcheck](https://github.com/w3c/epubcheck) on the problematic ePub?

**Comment by bitboxer** [comment]
Ah, found it. The html had tons of wrongly encoded characters.
