### ISSUE TITLE
top quarter of home screen filled with author names

### ISSUE THREAD

**Issue by RMHogervorst** [baskerville/plato#333]
Hi people,

I love the speed and simplicity of Plato, I have one minor annoyance, the top quarter of my screen is filled with authors, can I change that somewhere? Change it to series, or just remove it?

I'm using a kobo Aura edition 2 version 1. and using plato 0.9.39

![IMG_20231102_104609](https://github.com/baskerville/plato/assets/9538040/14c0f58b-716b-404d-b6b1-c29ea0e0cb2c)

**Comment by baskerville** [comment]
> the top quarter of my screen is filled with authors

That's the [navigation bar](https://github.com/baskerville/plato/blob/master/doc/MANUAL.md#navigation-bar).

> or just remove it?

Swipe from below the bar to above it or set `navigation-bar` to `false` in _Settings.toml_.
