### ISSUE TITLE
Setting book read state when downloading via hooks subsystem

### ISSUE THREAD

**Issue by Church-** [baskerville/plato#337]
Hi there,

I'm currently working on modifying a plugin for grabbing books via OPDS.

Something I'd like to add to it is the ability to set the reading state of a book if the OPDS feed has that info/I can otherwise access it via API.

There are a number of books I keep on my e-reader for archival purposes that I'd like to automatically set as finished on download so they don't show up in my default search feed.

Correct me if I'm wrong but reading over the example code from the wallabag fetcher it seems like I'd just need to create a ReaderInfo json object as part of my info object before passing it via the addDocument event, no?

**Comment by baskerville** [comment]
> Correct me if I'm wrong but reading over the example code from the wallabag fetcher it seems like I'd just need to create a ReaderInfo json object as part of my info object before passing it via the addDocument event, no?

I'm afraid it won't work : the _reader_ field has the _serde_ attribute *skip* set.

**Comment by Church-** [comment]
Bothersome, is there a way around that?
Other then compiling a fork with the skip attribute changed to something more lax?
