### ISSUE TITLE
./plato: /lib/libc.so.6: version `GLIBC_2.18' not found (required by ./plato)

### ISSUE THREAD

**Issue by UnicodeAlt255** [baskerville/plato#34]
I installed plato-0.6.3 with KSM09, but whenever I touch the menu entry "start plato" nothing happens except for the screen flashing. A crash.log appears with this:
``./plato: /lib/libc.so.6: version `GLIBC_2.18' not found (required by ./plato)``

**Comment by UnicodeAlt255** [comment]
3.19.5761 (oeo28f3185, 12/29/15)

I never updated in fear of loss of hackability.

**Comment by geek1011** [comment]
Then that's probably why it doesn't work. The current versions are just as hackable as the older ones. The biggest difference is that the newer versions has the new non-tiled home screen.

You may be able to get it to work on 3.19.5761 by compiling it with an older glibc, if you want to do that.

**Comment by UnicodeAlt255** [comment]
I updated the firmware and it worked. Thanks.

**Comment by Trane9991** [comment]
Hey.
I'm using Kobo Mini v3.19.5761
Installed Plato as described here: https://www.mobileread.com/forums/showthread.php?t=314220

Clicking on plato starts loading and then failing back to the main screen.
In the crash.log I can see this error: `./plato: /lib/libc.so.6: version `GLIBC_2.18' not found (required by ./plato)`

Any ideas?

**Comment by geek1011** [comment]
You need to update to a 4.x firmware. 4.12.12111 works pretty well on the Mini (I've been using it for the last few months). Alternatively, you can probably statically compile plato with musl.
