### ISSUE TITLE
Plato Freezing After Waking on Kobo Glo HD

### ISSUE THREAD

**Issue by markpopham** [baskerville/plato#345]
Hello!
Using Plato 0.9.40 on a Kobo Glo HD I will get a frozen screen every twenty minutes or so of reading. This seems to happen mostly or more when I have put the ereader to sleep using the top button and have them turned it back on. The screen will freeze on the last page I had opened and will not change despite touches until I restart the device.

I have had this issue across several versions. I am installing Plato via the scripts provided on the MobileRead forums.

**Comment by loitq07** [comment]
This issue happened with my Kobo Aura One too. You can fix it by swiping the screens with all your 5 fingers insanely until the screen move, it takes you 2-3 seconds. Try it.

**Comment by baskerville** [comment]
This is a duplicate of #118.

**Comment by markpopham** [comment]
@baskerville ah closing now. However, @loitq07 's suggestion worked - just slapping at the thing for a couple of seconds rather than touching it eventually made it unlock. Not sure if that information can be folded into 118
