### ISSUE TITLE
doc: Clarification for highlights swipe sequences

### ISSUE THREAD

**Issue by randomnoise** [baskerville/plato#350]
I was not able to perform swipe sequences to move back and forth between highlights/annotations on `Aura Edition 2`.

Version: `Plato 0.9.40`

https://github.com/baskerville/plato/blob/70a98e455bc8519c7bb46605a09735b873844c42/doc/MANUAL.md?plain=1#L116-L117

- Single top left/right corner motions work, I can move between `bookmarks` per [MANUAL.md instruction](https://github.com/baskerville/plato/blob/70a98e4/doc/MANUAL.md?plain=1#L116).

- The sentence in the manual page is also ambigious. I couldn't be sure I was doing the correct sequence; is it multi top corner motion without lifting the finger or is it top corner motion repeated more than once?

**Comment by baskerville** [comment]
> * The sentence in the manual page is also ambiguous. I couldn't be sure I was doing the correct sequence; is it multi top corner motion without lifting the finger or is it top corner motion repeated more than once?

That's two simultaneous corner motions of the same type.

**Comment by randomnoise** [comment]
> That's two simultaneous corner motions of the same type.

Thank you for the clarification. I was able to do the motion you mentioned, so there is no bug. (I'll update the issue title accordingly.)

The reason for my confusion is that the simultaneous swipe sequences are grouped together and under a different category. That's why I thought moving between highlights was done with one-finger motions.

https://github.com/baskerville/plato/blob/70a98e455bc8519c7bb46605a09735b873844c42/doc/MANUAL.md?plain=1#L121-L124


You can close the issue, but does moving the `highlights/annotations` line to the `simultaneous swipe sequences` category make sense?
