### ISSUE TITLE
Much faster battery drain than stock

### ISSUE THREAD

**Issue by neabb** [baskerville/plato#355]
I wanted to raise the issue of battery drain with Plato on my Libra 2.  Running the latest version of Plato.

Whilst the drain is not particularly fast - my Kobo dies in several days - losing about 20 - 30% daily, stock drains over the span of several weeks.

I am happy to assist with any testing for this.

**Comment by rafcon-dev** [comment]
Likely same issue I've been having, check out the latest binary posted here:
https://github.com/baskerville/plato/issues/313

I'm going to test it for the next days, feel free to do the same

**Comment by neabb** [comment]
I have installed the new binary... will report back.  Thank you for involving me in this.

**Comment by roshavagarga** [comment]
@neabb Possibly may want to close or update this :)

**Comment by neabb** [comment]
> @neabb Possibly may want to close or update this :)

This latest update is the bee's knee's!  Very good battery life.  /closed
