### ISSUE TITLE
Japanese characters show up as blank characters on the menu.

### ISSUE THREAD

**Issue by skewerr** [baskerville/plato#36]
I skimmed the other issues, but I don't think this was addressed: all Japanese characters show up as blank squares for me.

Plato seems noticeably faster than nickel, and I'm considering switching to it, but titles like __盾の勇者の成り上がり #03__ show up as __□□□□□□□□□□ #03__ on the menu. I thought this was due to missing glyphs in the fonts available to plato, so I added `IPAGothic.ttf` to both `/fonts` and `/.adds/plato/fonts` in hopes that it'd fallback to the glyphs on that font. It didn't, the issue persists.

**Comment by baskerville** [comment]
There's no font fallback mechanism yet.

**Comment by skewerr** [comment]
Could I merge the glyphs from another font into the one Plato uses for the menu? If so, what is that font?

**Comment by baskerville** [comment]
I will fix this, don't worry. If you really can't wait, the font you want to *enhance* is *Noto Sans*.
