### ISSUE TITLE
Only two font options appear?

### ISSUE THREAD

**Issue by ollietheotter983** [baskerville/plato#368]
As seen below, i only have two font options even though Plato's font folder is loaded with fonts

Device is Kobo Clara HD
![17177021524814962311756883684501](https://github.com/baskerville/plato/assets/169618018/7ea3d42f-2b1c-47b1-920c-7475087da144)

**Comment by ollietheotter983** [comment]
Closing as I realised I had used the wrong font folder

**Comment by candideu** [comment]
How do I fix this?

**Comment by ollietheotter983** [comment]
I no longer have a Kobo but I realised I put the fonts in the wrong folder pretty much
