### ISSUE TITLE
Go to previous chapter only goes back to the beginning of the current chapter

### ISSUE THREAD

**Issue by jcornuz** [baskerville/plato#38]
Hi,

First (and I know this is weird in a bugreport): thanks and bravo for Plato! It has become my new daily driver on a Kobo Aura 2: it is snappy, UI makes a lot of sense (and is super elegant) plus it has everything needed to do the job (read books) while keeping things simple. Great stuff!

Now for the bug :/ the "go to previous chapter" (long tap on the left ear) only works when I am in the middle of a chapter - it goes back to the beginning of the curent chapter as expected. However it doesn't allow me to move further on to the chapter before - as it is possible to do with the "go to next chapter".

Let me know if this makes sense (or not) and again: thanks for Plato!

**Comment by baskerville** [comment]
Thank you for the kind words and for taking the time to read the manual.

This bug sounds familiar, what version of *Plato* are you running?

Can you share the affected document with me?

**Comment by jcornuz** [comment]
I am using 0.6.5 on a Kobo Aura 2

I will send you an example of a book that creates trouble by PM since it is not public domain ;)

Thanks for you prompt reaction!

**Comment by baskerville** [comment]
Thanks, I was able to reproduce.

I'll have to revise my approach to handling the TOC. Fortunately it will also allow me to get rid of the lag that occur when opening a TOC with links of the form `xyz#abc`.

**Comment by jcornuz** [comment]
Good luck! Looking forward to testing a future version (but still enjoying Plato in the meantime!)

Let me know if you need anything else from me.
