### ISSUE TITLE
Hyphens render as “O” on monospaced text

### ISSUE THREAD

**Issue by j0lol** [baskerville/plato#380]
Whenever a monospaced line is wrapped, the hyphen shows as O instead of -

this presents at the top of this “screenshot”:
![image](https://github.com/user-attachments/assets/05711d59-e619-419b-a67b-5b76f8c3c1d3)

**Comment by Prateek-coder19** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
