### ISSUE TITLE
Unable to start plato on aura 2

### ISSUE THREAD

**Issue by PhieF** [baskerville/plato#39]
Hi,
plato is correctly shown in ksm 09 but when selecting it, the ui blinks and nothing starts...

Any ideas why ? 

Thanks !

**Comment by baskerville** [comment]
Do you have a `crash.log` (in `.adds/plato`)?

**Comment by PhieF** [comment]
Hi,

here it is

```
./plato: /lib/libc.so.6: version `GLIBC_2.18' not found (required by ./plato)
```

thanks !

**Comment by baskerville** [comment]
*Plato* doesn't work on the 3.X firmwares. A recent 4.X firmware is required.
