### ISSUE TITLE
Suggestion: Select extensions to be parsed

### ISSUE THREAD

**Issue by JeanOlivier** [baskerville/plato#4]
Plato seems like it has a lot of potential. However I am not ready to ditch nickel anytime soon, so it'd need to coexist with it. 

Would it be possible to have a configuration file or menu with tick items in which we can select the extensions that will be included in plato? I'd like to exclude plain text files, html, etc., but keep epub/kepub/pdf/djvu.

Thanks et Bon Travail!

**Comment by baskerville** [comment]
You can now set the *allowed kinds* in `settings.json`:
```json
{
    "import": {
        "allowedKinds": ["epub", "pdf", "djvu"],
        "unmountTrigger": true
    }
}
```

Please note that *mupdf* doesn't handle the *kepub* file extension.
