### ISSUE TITLE
Does often not remember current page (Kobo Clara HD w/ KFMon

### ISSUE THREAD

**Issue by nicohansi** [baskerville/plato#44]
When powering off and on again the current page/progress is lost. The current page is, I am asuming, written when exiting a book to the main menu. This means when powering off or crashing Plato looses the progress since last exiting to the menu.
In case there is no good reason against it i would suggest saving the current page on a pageturn event instead.

**Comment by baskerville** [comment]
What version of *Plato* are you running?

**Comment by nicohansi** [comment]
I was running 0.6.7. after upgrading to 0.6.8 I could not reproduce the error. Thanks for your work. i will post another issue if the problem reappears.
