### ISSUE TITLE
[feature] Adding an eraser pen in Sketch

### ISSUE THREAD

**Issue by radalain** [baskerville/plato#45]
Currently we can only erase the whole page (with the "New" tab). 

Do you think it's possible to add in Sketch the ability to erase only parts of the note ?
(Instead of writing lines, we erase what we touch). 

It is currently partially doable using the white color pen over whatever we draw but the lines are still a little visible.

Thank you for your amazing job !

**Comment by baskerville** [comment]
The pale traces that are left when erasing with white are only present at the hardware level: you won't find them in the saved image. What I can do is add a menu item to do a full refresh.

**Comment by radalain** [comment]
Would the full refresh make the pale traces disappear from the screen ? If yes, then that would be perfect !

Would a go back / erase the very last stroke done button also work ? (Would act like a "ctrl+z").

Thank you again !

**Comment by Iey4iej3** [comment]
It would be easier if we can use the "erase" button on the stylet.
