### ISSUE TITLE
How are you syncing your content? 

### ISSUE THREAD

**Issue by cmorgan** [baskerville/plato#47]
Would be great to embed a web client / browser or even better an ssh server (e.g. dropbear) for syncing content.
How are u syncing at the moment? Surely not over USB?

**Comment by baskerville** [comment]
I'm syncing over USB. (I have an unusual setup that allows me to properly unmount `/mnt/onboard`.)

What I could do is add a menu item to trigger an automatic import.

**Comment by cmorgan** [comment]
Do you mean similar to a recursive wget from a webserver initiated from the device? That would be neat. Currently i have an rsync initiated on a PC connected via USB - but it's clunky.

**Comment by baskerville** [comment]
Sorry, I meant *fast* import.

You can already [automatically start an SSH server](https://www.yingtongli.me/blog/2018/07/30/kobo-ssh.html) on your device (@NiLuJe provides [pre-built `dropbear` binaries](https://www.mobileread.com/forums/showthread.php?t=225030)).
