### ISSUE TITLE
Can't change zoom mode to fit to width in non multi-touch devices (Glo)

### ISSUE THREAD

**Issue by slim** [baskerville/plato#48]
Kobo Glo does not support multitouch, it seems there is no way to change zoom mode without it

**Comment by baskerville** [comment]
If you tap the title label (in the top bar), it will bring up a menu with a *Zoom Mode* sub-menu.

**Comment by slim** [comment]
Thank you! My bad, I expected all the parameters to be in the hamburger menu, I did not look further.
