### ISSUE TITLE
Old books still visible. Method to "reset" library?

### ISSUE THREAD

**Issue by travisterrell** [baskerville/plato#49]
Hi,

I recently deleted all books from my device (not with any sort of factory reset--just by deleting files). I then readded them with a new and improved folder structure. Now, Plato lists duplicate entries for many books, with one entry that actually opens the book, and the other which does nothing when tapped. Presumably, Plato's database has entries pointing to both the "old" and "new" file paths?

Is there a way to purge/reset Plato's database, such that the old books/paths are removed from the list?

Thank you!

**Comment by baskerville** [comment]
As of *Plato* 0.7.1: tap the lower left books/matches count label. The library menu will appear: select *Clean Up*. This will remove all the entries with a dangling path.
