### ISSUE TITLE
with warm fronttlight getting to sleep make a blue flash

### ISSUE THREAD

**Issue by bricewge** [baskerville/plato#53]
Getting the device to sleep when the frontlight is used with a warmth setting generates a blue "flash". As if the warmth setting was unset before the frontlight was turned off. This doesn't happen in Kobo's software.

By the way I wanted to thanks you for all your awesome software (plato, sxhkd and bspwm) I have been using day-to-day for several years now, their user interface are very well thought out!

**Comment by bricewge** [comment]
I suspect it comes from here: https://github.com/baskerville/plato/blob/8ae908f6d6ca5a5690dfe8e2b5a7cbbe32417446/src/app.rs#L582-L583
https://github.com/baskerville/plato/blob/8ae908f6d6ca5a5690dfe8e2b5a7cbbe32417446/src/app.rs#L533-L534

I didn't managed to get the tool-chain up and running to test it myself though.

**Comment by baskerville** [comment]
Please check, using [this test binary](https://www.mobileread.com/forums/showpost.php?p=3846511&postcount=415), that all the issues are fixed.

**Comment by bricewge** [comment]
#50 isn't fixed. Thanks a lot for your hard work.
