### ISSUE TITLE
Some pages are skipped in epub

### ISSUE THREAD

**Issue by bricewge** [baskerville/plato#54]
When reading an epub I have find out that some pages are skipped when going forward. Going backward after the skipped page displays it but the page number is not updated when on the skipped page. The issue isn't present when using Kobo software.

> [A picture is worth a thousand words](https://0x0.st/zmjD.webm)

It happen at several places in the book.

**Comment by baskerville** [comment]
Can you reproduce using swipe gestures?

**Comment by bricewge** [comment]
Yes. Swipes, touch and physical buttons all produces the same behavior.

**Comment by baskerville** [comment]
Could you go through the scenario shown in the video again using the attached binary and post the resulting `info.log`?

[plato-0.7.1-debug1.zip](https://github.com/baskerville/plato/files/3198227/plato-0.7.1-debug1.zip)

**Comment by bricewge** [comment]
Here it is: [info.log](https://github.com/baskerville/plato/files/3198252/info.log).

**Comment by baskerville** [comment]
Thanks, unfortunately I wasn't able to spot the bug based on the given log.

Could you try again with the attached binary and post the resulting `info.log`? It would be great if you could open the ePUB just before the skipped page, move forward, move backward and close.

[plato-0.7.1-debug2.zip](https://github.com/baskerville/plato/files/3198557/plato-0.7.1-debug2.zip)

**Comment by bricewge** [comment]
That's already what I did for the first log . Here is the new one [info.log](https://github.com/baskerville/plato/files/3198602/info.log). After the bug is triggered  it seems that all the subsequent movements are messed up.

Maybe it would be easier if I send you the problematic file, no?

**Comment by baskerville** [comment]
> Maybe it would be easier if I send you the problematic file, no?

Yes, it might be preferable. Please send me the problematic ePUB (use the e-mail address given on my GitHub profile), your `Settings.toml`, and the entry in `.metadata.json` that represent the ePUB.

**Comment by baskerville** [comment]
Thanks, I was able to reproduce, the problem comes from these lines in the `reader` object of the entry that describes the problematic ePUB in `.metadata.json`:
```json
      "zoomMode": "FitToWidth",
      "topOffset": 1920,
```

What happened is that you (unintentionally?) performed a spread gesture, and since the call to `set_zoom_mode` isn't gated in this case (that's the actual bug), the zoom mode was changed (_fit-to-width_ makes no sense for dynamic formats). You can fix the problem by removing those lines from the relevant entry in `.metadata.json` (while *Plato* isn't running).

**Comment by bricewge** [comment]
Nice, it's fixed! Yes I randomly tried some gestures at some point but I didn't made the link between it and the bug. 

BTW, unrelated, I got a panic on a PDF but I wasn't able to reproduce do you want another bug report?

Hopefully I won't bother you again unless I manage to write a PR.

**Comment by baskerville** [comment]
> I got a panic on a PDF but I wasn't able to reproduce do you want another bug report?

Yes, please create a bug report with the relevant `crash.log`.
