### ISSUE TITLE
add plato-import in releases assets

### ISSUE THREAD

**Issue by bricewge** [baskerville/plato#58]
It would be nice to have `plato-import` in the release assets as a statically link binary for at least the most popular `x86_64`.

I'm struggling to build `plato` on NixOS for non arm platform (ie. without running `./build fast`) either through `./build slow` and with Nix specific tools.

**Comment by baskerville** [comment]
Here's a guide on how to build `plato-import` on *Linux*:

- Install the following dependencies with your package manager: *DjVuLibre*, *HarfBuzz*, *OpenJPEG*, *jpeg*, *jbig2dec*, *zlib*.
- Unpack the sources for *MuPDF* 1.15.0 and the attached archive in the same directory.
- Apply the patch and build the library (it will appear in `build/release`):
```sh
patch -p 1 < linux.patch
./build-linux.sh
```
- Within *Plato*'s directory, go to `src/wrapper` and build the wrapper (replace `<path_to_mupdf>` with the appropriate path):
```sh
CFLAGS="-I<path_to_mupdf>/include" ./build.sh
```

- Copy the generated libraries (`libmupdf.so` and `libmupdfwrapper.so`) in the appropriate directory (e.g. `/usr/lib`).

- And finally, in *Plato*'s directory (the binary is saved in `~/.cargo/bin`): 
```sh
cargo install --path . --bin plato-import --features importer
```
[mupdf-linux.zip](https://github.com/baskerville/plato/files/3427873/mupdf-linux.zip)
