### ISSUE TITLE
[plato-import] "Consolidate" leaves behind non-existent files

### ISSUE THREAD

**Issue by rien333** [baskerville/plato#62]
Part of managing a database is moving stuff around. `plato-import` makes this fairly easy, as it is able to recognize _new_ folders and files in the current `LIBRARY_PATH`. However, the consolidate flag  (`-C`), does not detect deleted/old files, although it cleans a great deal of the `metadata.json` file. 

Is the fact that deleted/moved files survive a `plato-import -C LIBRARY_PATH` call intentional, or is it something the `-C` flag should be able to handle?

**Comment by baskerville** [comment]
> Is the fact that deleted/moved files survive a `plato-import -C LIBRARY_PATH` call intentional, or is it something the `-C` flag should be able to handle?

The `--consolidate` command enhances the metadata but isn't meant to remove elements. Since there's already a *Clean Up* entry in the library menu that removes elements with dangling paths, I think it would be fine to mirror that in `plato-import`.

**Comment by rien333** [comment]
I missed that option! Feel free to close, or if you prefer, add a new flag to `plato-import` to clean.
