### ISSUE TITLE
Gesture mix-up in docs

### ISSUE THREAD

**Issue by rien333** [baskerville/plato#66]
What a great set of new changes! Thank you so much for all of your work!

From the `doc/MANUAL.md`:

```markdown
# Home & Reader
Tap the bottom left and top right corners to take a screenshot.

Tap the top left and bottom right corners to do a full screen refresh.
```
At the moment bottom left+top right does a screen refresh, and top left+bottom right does a screenshot.  So either something in the docs or in the code should be changed. 

(aside: if find these two gestures kinda hard to trigger. maybe allow rebinding a couple of gestures to commands of the user's preference? Maybe the new arrow gestures can be used for this purpose) 

Do you accept donations btw? Can't give much, but I also use bspwm as my daily driver so I use a lot of your software.

**Comment by baskerville** [comment]
Thanks, I might add a setting to allow the user to fine tune the area of the corner regions.

I think the key here is to try to find the right balance between not being able to perform the gestures consistently and triggering the gestures unintentionally.

You'll find a donation link at the end of this project's README.

**Comment by rien333** [comment]
> Thanks, I might add a setting to allow the user to fine tune the area of the corner regions.
> 
> I think the key here is to try to find the right balance between not being able to perform the gestures consistently and triggering the gestures unintentionally.

After using plato 0.7.7 for a while, I noticed that I definitely trigger more actions unintentionally than before. In particular, I trigger a lot of searches and frontlight toggles by accident, even when doing single taps. Maybe my touch screen is busted - although I've no reason to believe so - but if it's possible to change the gesture sensitivity or trigger area that would be great. (Maybe my fingers are big and trigger a lot of different inputs during one tap?)

Could open a new issue if I document things a little more thoroughly, but I haven't really found a way to reproduce anything consistently yet.
