### ISSUE TITLE
`plato-import` build problems

### ISSUE THREAD

**Issue by rien333** [baskerville/plato#67]
**EDIT:** Was looking at the wrong file (`doc/LIBRARY.md` instead of `doc/IMPORTER.md`). Still, it might be a good idea to remove the `plato-import` build instructions from `doc/LIBRARY.md`, and maybe refer to `doc/IMPORTER.md` for the build process.

**Comment by rien333** [comment]
Further problem now following the correct instruction from `doc/LIBRARY.md`:

```bash
CFLAGS=".../mupdf-1.16.0-source/include"   ./build.sh
gcc: warning: /home/rw/Devil/mupdf-1.16.0-source/include: linker input file unused because linking not done
```

Only builds libmupdfwrapper.so, and not libmupdf.so

**Comment by baskerville** [comment]
> Further problem, now following the correct instructions from `doc/IMPORTER.md`:
> 
> ```shell
> CFLAGS=".../mupdf-1.16.0-source/include"   ./build.sh
> gcc: warning: /home/rw/Devil/mupdf-1.16.0-source/include: linker input file unused because linking not done
> ```

The correct value for `CFLAGS` is `-I<path_to_mupdf>/include`.

> This only builds libmupdfwrapper.so, and not libmupdf.so.

`libmupdf.so` is built on step 3.

> `plato-import` does build fine in the end though, maybe because I have `libmupdf` installed from my package manager?

What's your package manager?

**Comment by rien333** [comment]
Apparently I have trouble reading :) . 

> What's your package manager?

pacman, I happen to have `libmupdf v1.16.1` installed, which provides me with (among other things) `/usr/lib/libmupdf.a` and `/usr/lib/libmupdf-third.a`. I suppose `plato-import` happens to build fine with those libraries.
