### ISSUE TITLE
Can't write to SD card

### ISSUE THREAD

**Issue by ben4ever** [baskerville/plato#77]
Plato can't write to the SD card since it seems to be mounted read-only:

```
Plato is running on a Kobo Aura H₂O.
The framebuffer resolution is 1080 by 1440.
bible/esv_study_bible.epub
plato: Can't save metadata.
plato: Can't create data file.
plato: Read-only file system (os error 30)
```

I'm using v0.7.9.

**Comment by baskerville** [comment]
The fix for this problem is in [plato-launcher-fmon-0.7.9.zip](https://github.com/baskerville/plato/releases/download/0.7.9/plato-launcher-fmon-0.7.9.zip).

**Comment by ben4ever** [comment]
I use KSM 09. Could that be the reason that fixes from the fmon launcher aren't included for KSM?

**Comment by baskerville** [comment]
Unfortunately yes.

You might want to contact the author of *KSM* and ask him to include [this line](https://github.com/baskerville/plato/blob/cf39e6075634d7b90521f38a6a355ce8b607f82e/launchers/fmon/plato.sh#L10) in its launcher script.

**Comment by ben4ever** [comment]
I created a patch for KSM to add the line quoted by you to `adds/kbmenu/onstart/start_plato.sh`. If you want you could add it to the assets on the Releases page.

To install it, simply copy `KoboRoot.tgz` into `.kobo` directory on onboard storage and install it by clicking on `handle update` on the KSM home screen.

Patch can be downloaded [here](https://share-ben-dopplinger-org.s3.amazonaws.com/KoboRoot.tgz).
