### ISSUE TITLE
[feature] let auto-rotation be a global value when the gyroscope is used

### ISSUE THREAD

**Issue by bricewge** [baskerville/plato#78]
At the moment, auto-rotation value seems to be kept for each book and even different part of plato interface (the list of books and the indexes).

The issue is obvious when using a device with a gyroscope and an asymmetrical form factor, like the Kobo Forma; the navigation buttons are only on one side of the device. In this example let set the "Gyroscope" value to "Portrait" and start on the book list with device's buttons on the right ("Rotate" value is "90"). Let's open a book for the first time, it's the correct way up, now we take the device on the left hand, the buttons are on the left ("Rotate" value is "270") and the text is still in the right way up. However when we go back to the books list it's upside down ("Rotate" value is "90") because it remember this orientation from the last time the view was open, to get it to be the right way up you need to shake the device vigorously which is annoying on a day-to-day basis.
Note that it also appear if you rotate the device while being in an book index, then exiting it will return to the book being upside down. And also when opening back a book from the books list with a different orientation.

When a device has a "Gyroscope" which isn't set to "Ignore" `plato` should either ignore the saved rotation settings of the books or apply the current rotation value on each change of view and not wait for a rotation event (like a good shaking from the user) to do so.

Thank you for your awesome work on `plato` @baskerville I couldn't use my e-reader without it now!

**Comment by baskerville** [comment]
Perhaps there should be a way to tie a book to a particular orientation though?

**Comment by bricewge** [comment]
In what I previously suggest, setting "Gyroscope" to ignore would allow tying a book to specific orientation.

But thinking about this issue a bit more it seems more complex that what I first thought. A badly oriented PDF like [this one](http://bee.mif.pg.gda.pl/ciasteczkowypotwor/Metrix/OX710A.pdf) can't currently be read easily, rotating can make it upright but but then the UI isn't, which is bummer. But maybe this isn't in `plato`'s scope and orienting the document should be done off-device?

**Comment by baskerville** [comment]
> But maybe this isn't in *Plato*'s scope and orienting the document should be done off-device?

Yes, the example PDF is just a set of bitmap images.

The proper way to proceed would be to:
- Extract the images with *Poppler*.
- Rotate and extract the single pages with *ImageMagick*.
- Create a DjVu document with *DjVuLibre*, *tesseract* and *ocrodjvu*.
