### ISSUE TITLE
[dictionary view] Don't show page navigation arrow if there is only one page

### ISSUE THREAD

**Issue by rien333** [baskerville/plato#82]
Great job on the dictionary support! I was able to get wordnet working. 

However, wordnet is the only dictionary I've installed. Yet, currently, plato shows an arrow for navigating to next dictionary (?) in the bottom-right corner. Pressing it does nothing, but it does remove the arrow. 

Maybe leave the arrow out if there is just one dictionary? It seems a bit confusing atm. Or does it have some other purpose? 

My `dictionaries/` folder contains a `wn.dict` and `wn.index` file.

FIY, it might be nice for new users if the `dictionaries/` folders was created automatically. I wasn't sure where to put it, but figured it out by looking at the source code.

**Comment by rien333** [comment]
Oh, it's for navigating to the next page of a definition.

**Comment by baskerville** [comment]
Could you provide some steps on how to reproduce?

**Comment by rien333** [comment]
Sorry for the vague descriptions. Here are the steps to reproduce:

1. Install a dictionary, as per the instructions from the manual
2. Go to "Applications  > dictionary" from the homepage
3. The view now has an arrow in the bottom-right corner (as if you could navigate to a new page, although pressing it achieves nothing much)

This is very minor "problem" btw, but it confused me initially. Feel free to close if you don't care.
