### ISSUE TITLE
[request] Enable fuzzy dictionary search by default

### ISSUE THREAD

**Issue by rien333** [baskerville/plato#83]
I've noticed when I define words in a pdf, they are often just one "Levenshtein" away from a dictionary entry (e.g. the pluralization of "credence" → "credences"). Fuzzy search is a great solution for this, but the "fuzzy" option does not  stay enabled after it has been used. 

Given that a Levenshtein distance of ≤ 1 is fairly conservative and will only rarely result in a false positive, I propose to make an configurable option to have fuzzy search on by default. (I wonder what has higher probability: getting a false positive from the dictionary, or users searching for words that are just one "Levenshtein" away. Plurals definitely seem to be common). I'm not 100% sure if this is a good idea in practice, however.

**Comment by baskerville** [comment]
I took me a while but I finally managed to produce a version of [WordNet 3.1 with headword inflections](https://www.mobileread.com/forums/showpost.php?p=4006583&postcount=772).

The fuzzy strategy is only meant to be used when you're unsure about a word's spelling.
