### ISSUE TITLE
Can't select font

### ISSUE THREAD

**Issue by dg01d** [baskerville/plato#88]
(Aura ONE)

When I choose the Font selector in the bottom part of the menu, only the current font (Literature) is available to select. The dropdown menu is covered by the initial state of the selector, and no other options are available.

I fixed it (for *me*) by replacing Literature in the fonts folder with my chosen font, retitled to the same name, and it works fine, but this is (clearly) suboptimal.

**Comment by baskerville** [comment]
> When I choose the Font selector in the bottom part of the menu, only the current font (Literature) is available to select.

The default font path is `/mnt/onboard/fonts` (the corresponding setting is `reader.font-path`).

**Comment by dg01d** [comment]
that doesn't help any.

the selector in the UI is non-functional, you can't change the font, even when you have more fonts installed in that folder.

**Comment by baskerville** [comment]
What's the output of `find /mnt/onboard/fonts`?

**Comment by dg01d** [comment]
where/how should I run that command?

**Comment by baskerville** [comment]
Can you access the *fonts* directory on the internal SD card?

**Comment by dg01d** [comment]
oh, sure;

```
/Volumes/KOBOeReader
❯ exa --tree fonts
fonts
├── Alegreya-Bold.ttf
├── Alegreya-BoldItalic.ttf
├── Alegreya-Italic.ttf
├── Alegreya-Regular.ttf
├── Bitter-Bold.otf
├── Bitter-BoldItalic.otf
├── Bitter-Italic.otf
├── Bitter-Regular.otf
├── Bookerly-Bold.ttf
├── Bookerly-BoldItalic.ttf
├── Bookerly-Italic.ttf
├── Bookerly-Regular.ttf
├── Literata-Bold.otf
├── Literata-BoldItalic.otf
├── Literata-Italic.otf
└── Literata-Regular.otf
```

**Comment by baskerville** [comment]
What's the output of `grep font-path Settings.toml`?

**Comment by endverbraucher** [comment]
I've got the same problem on a clara hd.

The fonts directory:
```
/Volumes/KOBOeReader/fonts
❯ exa --tree
.
├── Bitter-Bold.otf
├── Bitter-BoldItalic.otf
├── Bitter-Italic.otf
├── Bitter-Regular.otf
├── FiraSans-Bold.ttf
├── FiraSans-BoldItalic.ttf
├── FiraSans-Italic.ttf
├── FiraSans-Regular.ttf
├── Merriweather-Bold.otf
├── Merriweather-BoldItalic.otf
├── Merriweather-Italic.otf
├── Merriweather-Regular.otf
├── SourceSansPro-Bold.otf
├── SourceSansPro-BoldItalic.otf
├── SourceSansPro-Italic.otf
├── SourceSansPro-Regular.otf
├── Vollkorn-Bold.otf
├── Vollkorn-BoldItalic.otf
├── Vollkorn-Italic.otf
└── Vollkorn-Regular.otf
```

and `grep font-path Settings.toml` output is `font-path = "/mnt/onboard/fonts"`

**Comment by bosel** [comment]
Confirmed, 0.81 on Clara HD

**Comment by baskerville** [comment]
@endverbraucher Could you try the attached binary and post the contents of `info.log`?

[plato-0.8.2-test1.zip](https://github.com/baskerville/plato/files/4122814/plato-0.8.2-test1.zip)

**Comment by endverbraucher** [comment]
Sure! Looks much better now! I can see all my fonts and apply them. `info.log` doesn't containing anything to worry about:

```
Plato is running on a Kobo Clara HD.
The framebuffer resolution is 1072 by 1448.
books/Code Simplicity - Max Kanat-Alexander.epub
```

**Comment by tootbrute** [comment]
I think this is probably still an issue. 

I just installed the latest Plato release last night, Plato 0.19.1and by default in Settings.toml is: font-path = "/mnt/onboard/fonts"

I edited it to /mnt/onboard/.adds/plato/fonts and not it works just fine. Seems it should default to this directory.

This is on my Kobo Clara HD.

**Comment by jfly** [comment]
I just ran into the exact same issue as @tootbrute.

@baskerville, is this a bug, or some sign of misconfiguration on my part?

**Comment by baskerville** [comment]
I'm not sure I'm following : what's the issue exactly? What @tootbrute wrote doesn't make sense : if you have fonts in */mnt/onboard/fonts* (that's the path for custom user fonts in *Nickel*) then they should appear in the font selection menu or you should see errors in *info.log* mentioning the fonts that couldn't be loaded. The default font path will not be */mnt/onboard/.adds/plato/fonts*, this directory should be left alone : it contains the fonts used for the user interface. The only relevant serif font in this directory is provided as a synthetic entry in the font selection menu.

**Comment by jfly** [comment]
@baskerville that explains it! I was under the mistaken impression that `/mnt/onboard/fonts` was always supposed to exist, and that it contains all the fonts nickel uses. Now I understand that that folder is *only* for custom fonts and the default fonts nickel uses are baked into the OS... somewhere.

I was extra confused because I am coming from KOReader, which did have a selection of fonts that I never configured. After some digging, I see that that's simply because they bake a number of fonts into their build: https://github.com/koreader/koreader/tree/v2023.10/resources.

Here's an attempt to avoid future confusion for people: https://github.com/baskerville/plato/pull/334

**Comment by baskerville** [comment]
> the default fonts nickel uses are baked into the OS... somewhere.

And they are encrypted.

**Comment by candideu** [comment]
I'm having the same problem, and don't quite understand how to get the longer list of selectable fonts... I downloaded Plato from here: https://www.mobileread.com/forums/showthread.php?t=314220
