### ISSUE TITLE
Frontlight doesn't turn on

### ISSUE THREAD

**Issue by dg01d** [baskerville/plato#89]
(Aura ONE)

When I select the frontlight icon, or even when I use the physical switch, the *icon* changes, but the *light* does not turn on.

**Comment by baskerville** [comment]
You can toggle the frontlight by tapping and holding the frontlight icon: you might have done that unintentionally.

**Comment by dg01d** [comment]
Sorry, @baskerville, but I've tried toggling the frontlight using both the physical switch *and* the icon. Neither work. The icon *changes* when I do either, but the light itself resolutely stays off.

**Comment by baskerville** [comment]
What's the contents of `info.log`?

**Comment by dg01d** [comment]
um....

```
Plato is running on a Kobo Aura.
The framebuffer resolution is 758 by 1024.
f/Velocity Weapon - Megan E. O'Keefe.epub
Went to sleep on January 24, 2020 at 00:29.
Woke up on January 24, 2020 at 03:11.
Went to sleep on January 24, 2020 at 03:14.
Woke up on January 24, 2020 at 03:17.
Went to sleep on January 24, 2020 at 03:33.
Woke up on January 24, 2020 at 03:33.
Went to sleep on January 24, 2020 at 03:49.
Woke up on January 24, 2020 at 03:49.
Went to sleep on January 24, 2020 at 04:05.
Woke up on January 24, 2020 at 04:06.
Went to sleep on January 24, 2020 at 04:22.
Woke up on January 24, 2020 at 04:22.
Went to sleep on January 24, 2020 at 04:38.
Woke up on January 24, 2020 at 04:38.
Went to sleep on January 24, 2020 at 04:54.
Woke up on January 24, 2020 at 06:03.
Went to sleep on January 24, 2020 at 09:08.
Woke up on January 24, 2020 at 11:14.
Went to sleep on January 24, 2020 at 11:51.
Woke up on January 24, 2020 at 14:32.
Went to sleep on January 24, 2020 at 14:41.
Woke up on January 24, 2020 at 14:44.
Went to sleep on January 24, 2020 at 15:08.
Woke up on January 25, 2020 at 18:46.
```

**Comment by baskerville** [comment]
What happens when you tap the frontlight icon?

**Comment by dg01d** [comment]
It turns on/off - the icon, not the actual **light**

Thanks for even answering me, by the way. I love how light this reader is.

**Comment by baskerville** [comment]
> It turns on/off - the icon

This is strange: it would mean that every tap you perform is seen as a tap and hold. That would make the UI unusable.

**Comment by dg01d** [comment]
Nono, I mean,

If Icon is Off, tapping it turns it on. 

And vice versa.

**Comment by baskerville** [comment]
> If Icon is Off, tapping it turns it on.

Do you understand the difference between a *tap* and a *tap-and-hold*?
