### ISSUE TITLE
How to test on desktop

### ISSUE THREAD

**Issue by iwanb** [baskerville/plato#9]
Hi,

I was wondering if you have a setup to test the application on a desktop? Or do you always run it on the kobo?

Regards,
Iwan

**Comment by baskerville** [comment]
I have a test file that renders components using the `ImageFramebuffer` implementation of the `Framebuffer` trait. I generate events manually and save the framebuffer content as PNG on each significant frame.

**Comment by iwanb** [comment]
Ok thank you, I see the fake classes now.
Wouldn't it make sense to create a WindowFramebuffer or something that runs on a window manager?
In any case, could you share your test file?

**Comment by baskerville** [comment]
As of 40fe5b0, you can build the emulator with:
```sh
cargo build --release --bin plato-emulator --features emulator
```
And run it with:
```sh
PRODUCT=star ./target/release/plato-emulator
```
