### ISSUE TITLE
Unable to build, libstdc++.so.6 is needed by libs/libdjvulibre.so, incorrect ld from gcc, should be g++?

### ISSUE THREAD

**Issue by Aszarsha** [baskerville/plato#90]
Hello,

I tried to build plato both using `./build.sh` (default fast path) and `./build.sh slow`.
I have a local arm-linux-gnueabihf GCC 9.2.0 toolchain (which does includes `libstdc++.so.6`).

In both cases (fast and slow), the reported error is that `/usr/bin/arm-linux-gnueabihf-ld` fails with multiple undefined reference in `libs/libdjvulibre.so`.
Going up the trace, it seems that linking is called from `arm-linux-gnueabihf-gcc`:
``error: linking with `arm-linux-gnueabihf-gcc` failed: exit code: 1``

It probably should be called with `arm-linux-gnueabihf-g++` instead, isn't it?

**Comment by baskerville** [comment]
You need to use the compiler toolchain mentioned [here](https://github.com/baskerville/plato/pull/75#issuecomment-567135635).

**Comment by Aszarsha** [comment]
Yes, thank you. I actually had figured that out in the meantime but the issue remains: even if the 4.9 toolchain somehow links with the libstdc++ automatically, it **is** a dependency of libdjvulibre.so. Should it not be specified in the build.rs script? (see PR)

kobolabs seemed to have exceeded their LFS quota and I could not download the toolchain. However, I used the minimal one (no library included) from Linaro and it worked quite well: use `gcc-linaro-4.9.4-2017.01-x86_64_arm-linux-gnueabihf.tar.xz` from [the Linaro releases archive](https://releases.linaro.org/components/toolchain/binaries/4.9-2017.01/arm-linux-gnueabihf/).
It allowed me to `./build.sh slow` all dependencies and have a working build running on my Libra.
