### ISSUE TITLE
Gyroscope rotations are inverted on Libra H₂O

### ISSUE THREAD

**Issue by Aszarsha** [baskerville/plato#92]
Kobo Libra H₂O with 4.19 firmware.
Plato custom build from master branch.

The interface is in standard position when then device is actually rotated with buttons on top.
The interface is in rotated position (top of the interface on the same side as the device physical buttons) when the device is actually in normal position.
Same inverted rotations with the two other positions.

**Comment by baskerville** [comment]
It should be fixed by 8c6f1614201a46377e4c21875fa335687627917a.

**Comment by baskerville** [comment]
In fact I've misread the report: `transformed_gyroscope_rotation` isn't right.

**Comment by baskerville** [comment]
Fixed by a5237d0f094329a6b34ca26fb00ff65bf11b55cc.
