### ISSUE TITLE
Unable to build the emulator: should be a matter a calling the right build script

### ISSUE THREAD

**Issue by Aszarsha** [baskerville/plato#98]
The `build.sh` and all its subscripts, including third party libraries building, are tailored for building an arm binary.

Third party dependencies aside, which should be installed with the system package manager, the`mupdfwrapper.so` wrapper still have to be built for the host architecture.
Even though a manual call to `build.sh` inside `src/wrapper` builds a library for the host arch, cargo is still unable to link with the library. Manually copying the host `mupdfwrapper.so` inside `libs` or adding `-L src/wrapper` to the build script does not work either.

**Comment by baskerville** [comment]
I've added some [instructions](https://github.com/baskerville/plato/blob/master/doc/EMULATOR.md).

The `build.sh` might indeed handle the intermediary steps (2 to 5).

**Comment by Aszarsha** [comment]
> I've added some [instructions](https://github.com/baskerville/plato/blob/master/doc/EMULATOR.md).

Great! It still doesn't work, cf [#99 ](https://github.com/baskerville/plato/issues/99), but the documentation is nice to have. Reverse engineering project building, all its dependencies and unspecified expectations, is not fun.

> The `build.sh` might indeed handle the intermediary steps (2 to 5).

I don't think that the `./build.sh` script should touch `/usr/lib` though, but 3 to 6 are optional anyway when libmupdf is handled by the package manager. I see that the `.patch` is only to prevent building unnecessary binaries and Plato does not require a patched version.

If that were to be the case, maybe Plato should statically link with its mupdf dependencies?

On a related note, maybe Plato should statically link with all its thirdparty dependencies that are not provided by the Kobo firmware? It would remove one distribution directory hence reducing potentiality for problems.
And I indeed did have a problem: some libraries were erroneously sent by ftp in ascii instead of binary mode and Plato then crashed unexpectedly. Needless to say: it was painful to debug.

**Comment by Aszarsha** [comment]
#101 fixed the issue.
